local STOCKING = {
    { label = "Glass", name = "minecraft:glass", damage = 0, stock = 64 },
    { label = "Chest", name = "minecraft:chest", damage = 0, stock = 64 },
    -- 	{label="Block of Diamond",name="minecraft:diamond_block",damage=0,stock=64},
    -- 	{label="Pressure Plate",name="minecraft:stone_pressure_plate",damage=0,stock=64},
    -- 	{label="Button",name="minecraft:stone_button",damage=0,stock=64},
    -- 	{label="Iron Bars",name="minecraft:iron_bars",damage=0,stock=64},
    -- 	{label="Weighted Pressure Plate (Heavy)",name="minecraft:heavy_weighted_pressure_plate",damage=0,stock=64},
    -- 	{label="Reinforced Glass",name="IC2:blockAlloyGlass",damage=0,stock=64},
    -- 	{label="Quartz Glass",name="appliedenergistics2:tile.BlockQuartzGlass",damage=0,stock=64},
    -- 	{label="Iron Ingot",name="minecraft:iron_ingot",damage=0,stock=64},
    -- 	{label="Gold Ingot",name="minecraft:gold_ingot",damage=0,stock=64},
    -- 	{label="Water Bucket",name="minecraft:water_bucket",damage=0,stock=1},
    -- 	{label="Lava Bucket",name="minecraft:lava_bucket",damage=0,stock=1},
    -- 	{label="Clay",name="minecraft:clay_ball",damage=0,stock=64},
    -- 	{label="Glass Bottle",name="minecraft:glass_bottle",damage=0,stock=64},
     	{label="Eye of Ender",name="minecraft:ender_eye",damage=0,stock=64},
    -- 	{label="ME Drive",name="appliedenergistics2:tile.BlockDrive",damage=0,stock=64},
    -- 	{label="ME Chest",name="appliedenergistics2:tile.BlockChest",damage=0,stock=64},
    -- 	{label="ME Interface",name="appliedenergistics2:tile.BlockInterface",damage=0,stock=64},
    -- 	{label="Crafting Unit",name="appliedenergistics2:tile.BlockCraftingUnit",damage=0,stock=64},
    -- 	{label="Crafting Co-Processing Unit",name="appliedenergistics2:tile.BlockCraftingUnit",damage=1,stock=64},
    -- 	{label="Arcane Stone Block",name="Thaumcraft:blockCosmeticSolid",damage=6,stock=64},
    -- 	{label="Air Crystal Cluster",name="Thaumcraft:blockCrystal",damage=0,stock=64},
    -- 	{label="Fire Crystal Cluster",name="Thaumcraft:blockCrystal",damage=1,stock=64},
    -- 	{label="Water Crystal Cluster",name="Thaumcraft:blockCrystal",damage=2,stock=64},
    -- 	{label="Earth Crystal Cluster",name="Thaumcraft:blockCrystal",damage=3,stock=64},
    -- 	{label="Order Crystal Cluster",name="Thaumcraft:blockCrystal",damage=4,stock=64},
    -- 	{label="Entropy Crystal Cluster",name="Thaumcraft:blockCrystal",damage=5,stock=64},
    -- 	{label="Mixed Crystal Cluster",name="Thaumcraft:blockCrystal",damage=6,stock=64},
    -- 	{label="Arcane Pedestal",name="Thaumcraft:blockStoneDevice",damage=1,stock=64},
    -- 	{label="Thickened Glass",name="ExtraUtilities:decorativeBlock2",damage=0,stock=64},
    -- 	{label="Obsidian Glass",name="ExtraUtilities:decorativeBlock2",damage=5,stock=64},
    -- 	{label="Clear Glass",name="TConstruct:GlassBlock",damage=0,stock=64},
    -- 	{label="Rune of the Orb",name="AWWayofTime:AlchemicalWizardrybloodRune",damage=3,stock=64},
    -- 	{label="Rune of Superior Capacity",name="AWWayofTime:AlchemicalWizardrybloodRune",damage=4,stock=64},
    -- 	{label="Speed Rune",name="AWWayofTime:speedRune",damage=0,stock=64},
    -- 	{label="Ritual Stone",name="AWWayofTime:ritualStone",damage=0,stock=64},
    -- 	{label="Imperfect Ritual Stone",name="AWWayofTime:imperfectRitualStone",damage=0,stock=64},
    -- 	{label="Crystal Cluster",name="AWWayofTime:blockCrystal",damage=0,stock=64},
    -- 	{label="Tank",name="BuildCraft|Factory:tankBlock",damage=0,stock=64},
    -- 	{label="Iron Chest",name="IronChest:BlockIronChest",damage=0,stock=64},
    -- 	{label="Steel Chest",name="IronChest:BlockIronChest",damage=4,stock=64},
    -- 	{label="Obsidian Chest",name="IronChest:BlockIronChest",damage=6,stock=64},
    -- 	{label="Endoflame",name="Botania:specialFlower",damage=0,stock=64},
    -- 	{label="ULV Machine Hull",name="gregtech:gt.blockmachines",damage=10,stock=64},
    { label = "LV Machine Hull", name = "gregtech:gt.blockmachines", damage = 11, stock = 8 },
    { label = "MV Machine Hull", name = "gregtech:gt.blockmachines", damage = 12, stock = 8 },
    { label = "HV Machine Hull", name = "gregtech:gt.blockmachines", damage = 13, stock = 8 },
    { label = "EV Machine Hull", name = "gregtech:gt.blockmachines", damage = 14, stock = 8 },
    { label = "IV Machine Hull", name = "gregtech:gt.blockmachines", damage = 15, stock = 8 },
     	{label="LuV Machine Hull",name="gregtech:gt.blockmachines",damage=16,stock=4},
    -- 	{label="EV Dynamo Hatch",name="gregtech:gt.blockmachines",damage=34,stock=64},
    -- 	{label="IV Dynamo Hatch",name="gregtech:gt.blockmachines",damage=35,stock=64},
    -- 	{label="HV Energy Hatch",name="gregtech:gt.blockmachines",damage=43,stock=64},
    -- 	{label="EV Energy Hatch",name="gregtech:gt.blockmachines",damage=44,stock=64},
    -- 	{label="IV Energy Hatch",name="gregtech:gt.blockmachines",damage=45,stock=64},
    -- 	{label="LuV Energy Hatch",name="gregtech:gt.blockmachines",damage=46,stock=64},
    -- 	{label="Input Hatch (ULV)",name="gregtech:gt.blockmachines",damage=50,stock=64},
    -- 	{label="Input Hatch (LV)",name="gregtech:gt.blockmachines",damage=51,stock=64},
     	{label="Input Hatch (HV)",name="gregtech:gt.blockmachines",damage=53,stock=2},
    -- 	{label="Input Hatch (IV)",name="gregtech:gt.blockmachines",damage=55,stock=64},
    -- 	{label="Output Hatch (ULV)",name="gregtech:gt.blockmachines",damage=60,stock=64},
     	{label="Output Hatch (HV)",name="gregtech:gt.blockmachines",damage=63,stock=2},
    -- 	{label="Input Bus (ULV)",name="gregtech:gt.blockmachines",damage=70,stock=64},
     	{label="Input Bus (LV)",name="gregtech:gt.blockmachines",damage=71,stock=2},
     	{label="Input Bus (HV)",name="gregtech:gt.blockmachines",damage=73,stock=2},
    -- 	{label="Output Bus (ULV)",name="gregtech:gt.blockmachines",damage=80,stock=64},
     	{label="Output Bus (LV)",name="gregtech:gt.blockmachines",damage=81,stock=2},
     	{label="Output Bus (HV)",name="gregtech:gt.blockmachines",damage=83,stock=2},
    -- 	{label="Fluid Drilling Rig II",name="gregtech:gt.blockmachines",damage=141,stock=64},
    -- 	{label="Quadruple Input Hatch (EV)",name="gregtech:gt.blockmachines",damage=200,stock=64},
    -- 	{label="Fluid Drilling Rig",name="gregtech:gt.blockmachines",damage=1157,stock=64},
    -- 	{label="1x Lead Cable",name="gregtech:gt.blockmachines",damage=1226,stock=64},
    -- 	{label="1x Tin Wire",name="gregtech:gt.blockmachines",damage=1240,stock=64},
    -- 	{label="1x Tin Cable",name="gregtech:gt.blockmachines",damage=1246,stock=64},
    -- 	{label="2x Cupronickel Wire",name="gregtech:gt.blockmachines",damage=1341,stock=64},
    -- 	{label="1x Cupronickel Cable",name="gregtech:gt.blockmachines",damage=1346,stock=64},
    -- 	{label="1x Copper Wire",name="gregtech:gt.blockmachines",damage=1360,stock=64},
    -- 	{label="1x Copper Cable",name="gregtech:gt.blockmachines",damage=1366,stock=64},
    -- 	{label="4x Copper Cable",name="gregtech:gt.blockmachines",damage=1368,stock=64},
    -- 	{label="1x Annealed Copper Wire",name="gregtech:gt.blockmachines",damage=1380,stock=64},
    -- 	{label="1x Annealed Copper Cable",name="gregtech:gt.blockmachines",damage=1386,stock=64},
    -- 	{label="1x Gold Wire",name="gregtech:gt.blockmachines",damage=1420,stock=64},
    -- 	{label="1x Gold Cable",name="gregtech:gt.blockmachines",damage=1426,stock=64},
    -- 	{label="4x Electrum Wire",name="gregtech:gt.blockmachines",damage=1442,stock=64},
    -- 	{label="2x Silver Wire",name="gregtech:gt.blockmachines",damage=1461,stock=64},
    -- 	{label="2x Silver Cable",name="gregtech:gt.blockmachines",damage=1467,stock=64},
    -- 	{label="4x Black Steel Wire",name="gregtech:gt.blockmachines",damage=1542,stock=64},
    -- 	{label="1x Aluminium Wire",name="gregtech:gt.blockmachines",damage=1580,stock=64},
    -- 	{label="2x Aluminium Wire",name="gregtech:gt.blockmachines",damage=1581,stock=64},
    -- 	{label="1x Aluminium Cable",name="gregtech:gt.blockmachines",damage=1586,stock=64},
    -- 	{label="2x Aluminium Cable",name="gregtech:gt.blockmachines",damage=1587,stock=64},
     	{label="4x Graphene Wire",name="gregtech:gt.blockmachines",damage=1602,stock=64},
    -- 	{label="1x Platinum Wire",name="gregtech:gt.blockmachines",damage=1640,stock=64},
    -- 	{label="1x Platinum Cable",name="gregtech:gt.blockmachines",damage=1646,stock=64},
    -- 	{label="1x Tungsten Wire",name="gregtech:gt.blockmachines",damage=1680,stock=64},
    -- 	{label="2x Tungsten Wire",name="gregtech:gt.blockmachines",damage=1681,stock=64},
    -- 	{label="1x Tungsten Cable",name="gregtech:gt.blockmachines",damage=1686,stock=64},
    -- 	{label="2x Tungsten Cable",name="gregtech:gt.blockmachines",damage=1687,stock=64},
    -- 	{label="2x HSS-G Wire",name="gregtech:gt.blockmachines",damage=1701,stock=64},
     	{label="1x Vanadium-Gallium Wire",name="gregtech:gt.blockmachines",damage=1740,stock=64},
    -- 	{label="1x Vanadium-Gallium Cable",name="gregtech:gt.blockmachines",damage=1746,stock=64},
    -- 	{label="1x Yttrium Barium Cuprate Wire",name="gregtech:gt.blockmachines",damage=1760,stock=64},
    -- 	{label="1x Yttrium Barium Cuprate Cable",name="gregtech:gt.blockmachines",damage=1766,stock=64},
    -- 	{label="1x Naquadah Wire",name="gregtech:gt.blockmachines",damage=1780,stock=64},
    -- 	{label="1x End Steel Wire",name="gregtech:gt.blockmachines",damage=1860,stock=64},
    -- 	{label="1x Red Alloy Wire",name="gregtech:gt.blockmachines",damage=2000,stock=64},
    -- 	{label="1x Superconductor Base IV Wire",name="gregtech:gt.blockmachines",damage=2260,stock=64},
    -- 	{label="1x Superconductor Base LuV Wire",name="gregtech:gt.blockmachines",damage=2280,stock=64},
    -- 	{label="1x Superconductor IV Wire",name="gregtech:gt.blockmachines",damage=2380,stock=64},
    -- 	{label="1x Superconductor LuV Wire",name="gregtech:gt.blockmachines",damage=2400,stock=64},
    -- 	{label="Bronze Fluid Pipe",name="gregtech:gt.blockmachines",damage=5122,stock=64},
    -- 	{label="Steel Fluid Pipe",name="gregtech:gt.blockmachines",damage=5132,stock=64},
    -- 	{label="Stainless Steel Fluid Pipe",name="gregtech:gt.blockmachines",damage=5142,stock=64},
    -- 	{label="Quadruple Stainless Steel Fluid Pipe",name="gregtech:gt.blockmachines",damage=5145,stock=64},
    -- 	{label="Titanium Fluid Pipe",name="gregtech:gt.blockmachines",damage=5152,stock=64},
    -- 	{label="Tungstensteel Fluid Pipe",name="gregtech:gt.blockmachines",damage=5162,stock=64},
    -- 	{label="Plastic Fluid Pipe",name="gregtech:gt.blockmachines",damage=5172,stock=64},
    -- 	{label="Large Plastic Fluid Pipe",name="gregtech:gt.blockmachines",damage=5173,stock=64},
    -- 	{label="Small Niobium-Titanium Fluid Pipe",name="gregtech:gt.blockmachines",damage=5181,stock=64},
    -- 	{label="Tiny Enderium Fluid Pipe",name="gregtech:gt.blockmachines",damage=5190,stock=64},
    -- 	{label="Small Electrum Item Pipe",name="gregtech:gt.blockmachines",damage=5611,stock=64},
    -- 	{label="PTFE Fluid Pipe",name="gregtech:gt.blockmachines",damage=5682,stock=64},
    -- 	{label="Large PTFE Fluid Pipe",name="gregtech:gt.blockmachines",damage=5683,stock=64},
    -- 	{label="2x HSS-S Wire",name="gregtech:gt.blockmachines",damage=11471,stock=64},
    -- 	{label="Solidifier Hatch I",name="gregtech:gt.blockmachines",damage=31781,stock=64},
    { label = "ULV Machine Casing", name = "gregtech:gt.blockcasings", damage = 0, stock = 8 },
    { label = "LV Machine Casing", name = "gregtech:gt.blockcasings", damage = 1, stock = 8 },
    { label = "MV Machine Casing", name = "gregtech:gt.blockcasings", damage = 2, stock = 8 },
    { label = "HV Machine Casing", name = "gregtech:gt.blockcasings", damage = 3, stock = 8 },
    { label = "EV Machine Casing", name = "gregtech:gt.blockcasings", damage = 4, stock = 8 },
    { label = "IV Machine Casing", name = "gregtech:gt.blockcasings", damage = 5, stock = 8 },
    { label = "LuV Machine Casing", name = "gregtech:gt.blockcasings", damage = 6, stock = 8 },
    -- 	{label="Bronze Plated Bricks",name="gregtech:gt.blockcasings",damage=10,stock=64},
    -- 	{label="Heat Proof Machine Casing",name="gregtech:gt.blockcasings",damage=11,stock=64},
    -- 	{label="Solid Steel Machine Casing",name="gregtech:gt.blockcasings2",damage=0,stock=64},
    -- 	{label="Frost Proof Machine Casing",name="gregtech:gt.blockcasings2",damage=1,stock=64},
    -- 	{label="Steel Gear Box Casing",name="gregtech:gt.blockcasings2",damage=3,stock=64},
    -- 	{label="Assembly Line Casing",name="gregtech:gt.blockcasings2",damage=5,stock=64},
    -- 	{label="Robust Tungstensteel Machine Casing",name="gregtech:gt.blockcasings4",damage=0,stock=64},
    -- 	{label="Clean Stainless Steel Machine Casing",name="gregtech:gt.blockcasings4",damage=1,stock=64},
    -- 	{label="Cupronickel Coil Block",name="gregtech:gt.blockcasings5",damage=0,stock=64},
    -- 	{label="HSS-G Coil Block",name="gregtech:gt.blockcasings5",damage=4,stock=64},
    -- 	{label="HSS-S Coil Block",name="gregtech:gt.blockcasings5",damage=9,stock=64},
    -- 	{label="Hermetic Casing I",name="gregtech:gt.blockcasings6",damage=1,stock=64},
    -- 	{label="Hermetic Casing III",name="gregtech:gt.blockcasings6",damage=3,stock=64},
    -- 	{label="Hermetic Casing V",name="gregtech:gt.blockcasings6",damage=5,stock=64},
    -- 	{label="Chemically Inert Machine Casing",name="gregtech:gt.blockcasings8",damage=0,stock=64},
    -- 	{label="Block of Ichorium",name="gregtech:gt.blockmetal8",damage=13,stock=64},
    -- 	{label="Block of Endereye",name="gregtech:gt.blockgem1",damage=7,stock=64},
    -- 	{label="Computer Case (Tier 2)",name="OpenComputers:case2",damage=0,stock=64},
    -- 	{label="Keyboard",name="OpenComputers:keyboard",damage=0,stock=64},
    -- 	{label="Transposer",name="OpenComputers:transposer",damage=0,stock=64},
    -- 	{label="Tumbaga Frame Box",name="miscutils:blockFrameGtTumbaga",damage=0,stock=64},
    -- 	{label="Potin Frame Box",name="miscutils:blockFrameGtPotin",damage=0,stock=64},
    -- 	{label="Inconel-625 Frame Box",name="miscutils:blockFrameGtInconel625",damage=0,stock=64},
    -- 	{label="Eglin Steel Frame Box",name="miscutils:blockFrameGtEglinSteel",damage=0,stock=64},
    -- 	{label="Watertight Steel Frame Box",name="miscutils:blockFrameGtWatertightSteel",damage=0,stock=64},
    -- 	{label="Talonite Frame Box",name="miscutils:blockFrameGtTalonite",damage=0,stock=64},
    -- 	{label="Hastelloy-X Frame Box",name="miscutils:blockFrameGtHastelloyX",damage=0,stock=64},
    -- 	{label="Iron Tank",name="irontank:ironTank",damage=0,stock=64},
    -- 	{label="Gold Tank",name="irontank:goldTank",damage=0,stock=64},
    -- 	{label="Pyrolyse Oven Casing",name="gregtech:gt.blockcasingsNH",damage=2,stock=64},
    -- 	{label="Material Press Machine Casing",name="miscutils:miscutils.blockcasings",damage=4,stock=64},
    -- 	{label="Maceration Stack Casing",name="miscutils:miscutils.blockcasings",damage=7,stock=64},
    -- 	{label="Sterile Farm Casing",name="miscutils:gtplusplus.blockcasings.2",damage=15,stock=64},
    -- 	{label="Volcanus Casing",name="miscutils:gtplusplus.blockcasings.3",damage=11,stock=64},
    -- 	{label="IsaMill Exterior Casing",name="miscutils:gtplusplus.blockcasings.5",damage=0,stock=64},
    -- 	{label="Solidifier Casing",name="gregtech:gt.blockcasings10",damage=13,stock=64},
    -- 	{label="Aluminium Frame Box",name="gregtech:gt.blockframes",damage=19,stock=64},
    -- 	{label="Titanium Frame Box",name="gregtech:gt.blockframes",damage=28,stock=64},
    -- 	{label="Invar Frame Box",name="gregtech:gt.blockframes",damage=302,stock=64},
    -- 	{label="Steel Frame Box",name="gregtech:gt.blockframes",damage=305,stock=64},
    -- 	{label="Stainless Steel Frame Box",name="gregtech:gt.blockframes",damage=306,stock=64},
    -- 	{label="Tungstensteel Frame Box",name="gregtech:gt.blockframes",damage=316,stock=64},
    -- 	{label="Polytetrafluoroethylene Frame Box",name="gregtech:gt.blockframes",damage=473,stock=64},
    -- 	{label="Energium Dust",name="IC2:itemDust2",damage=2,stock=64},
    -- 	{label="Mixed Metal Ingot",name="IC2:itemIngot",damage=4,stock=64},
    -- 	{label="Enriched Uranium Nuclear Fuel",name="IC2:itemUran",damage=0,stock=64},
    -- 	{label="MOX Nuclear Fuel",name="IC2:itemMOX",damage=0,stock=64},
    -- 	{label="Plutonium",name="IC2:itemPlutonium",damage=0,stock=64},
    -- 	{label="Tiny Pile of Uranium 235",name="IC2:itemUran235small",damage=0,stock=64},
    -- 	{label="Uranium 238",name="IC2:itemUran238",damage=0,stock=64},
    -- 	{label="Advanced Alloy",name="IC2:itemPartAlloy",damage=0,stock=64},
    { label = "Raw Carbon Fibre", name = "IC2:itemPartCarbonFibre", damage = 0, stock = 256 },
    -- 	{label="Iridium Reinforced Plate",name="IC2:itemPartIridium",damage=0,stock=64},
    -- 	{label="Energy Crystal",name="IC2:itemBatCrystal",damage=0,stock=1},
    { label = "Lapotron Crystal", name = "IC2:itemBatLamaCrystal", damage = 26, stock = 8 },
    -- 	{label="Empty Cell",name="IC2:itemCellEmpty",damage=0,stock=64},
    -- 	{label="Heat Exchanger",name="IC2:reactorHeatSwitch",damage=1,stock=1},
    -- 	{label="Advanced Heat Exchanger",name="IC2:reactorHeatSwitchDiamond",damage=1,stock=1},
    -- 	{label="Heat Vent",name="IC2:reactorVent",damage=1,stock=1},
    -- 	{label="Overclocked Heat Vent",name="IC2:reactorVentGold",damage=1,stock=1},
    -- 	{label="Advanced Heat Vent",name="IC2:reactorVentDiamond",damage=1,stock=1},
    -- 	{label="Industrial Diamond",name="IC2:itemPartIndustrialDiamond",damage=0,stock=64},
     	{label="Fluix Crystal",name="appliedenergistics2:item.ItemMultiMaterial",damage=7,stock=64},
     	{label="Fluix Dust",name="appliedenergistics2:item.ItemMultiMaterial",damage=8,stock=128},
    { label = "Printed Calculation Circuit", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 16, stock = 64 },
    { label = "Printed Engineering Circuit", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 17, stock = 64 },
    { label = "Printed Logic Circuit", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 18, stock = 64 },
    { label = "Printed Silicon", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 20, stock = 64 },
    { label = "Logic Processor", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 22, stock = 64 },
    { label = "Calculation Processor", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 23, stock = 64 },
    { label = "Engineering Processor", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 24, stock = 64 },
    -- 	{label="§e4k§r ME Storage Component",name="appliedenergistics2:item.ItemMultiMaterial",damage=36,stock=64},
    -- 	{label="§a16k§r ME Storage Component",name="appliedenergistics2:item.ItemMultiMaterial",damage=37,stock=64},
    -- 	{label="§b64k§r ME Storage Component",name="appliedenergistics2:item.ItemMultiMaterial",damage=38,stock=64},
    { label = "Formation Core", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 43, stock = 32 },
    { label = "Annihilation Core", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 44, stock = 32 },
    { label = "Blank Pattern", name = "appliedenergistics2:item.ItemMultiMaterial", damage = 52, stock = 32 },
    -- 	{label="Pattern Capacity Card",name="appliedenergistics2:item.ItemMultiMaterial",damage=54,stock=64},
    -- 	{label="§9256k§r ME Storage Component",name="appliedenergistics2:item.ItemMultiMaterial",damage=57,stock=64},
    { label = "ME Glass Cable - Fluix", name = "appliedenergistics2:item.ItemMultiPart", damage = 16, stock = 128 },
    -- 	{label="Illuminated Panel",name="appliedenergistics2:item.ItemMultiPart",damage=180,stock=64},
    -- 	{label="ME Storage Bus",name="appliedenergistics2:item.ItemMultiPart",damage=220,stock=64},
    -- 	{label="ME Level Emitter",name="appliedenergistics2:item.ItemMultiPart",damage=280,stock=64},
    -- 	{label="ME Terminal",name="appliedenergistics2:item.ItemMultiPart",damage=380,stock=64},
    -- 	{label="ME Storage Monitor",name="appliedenergistics2:item.ItemMultiPart",damage=400,stock=64},
    { label = "ME Interface", name = "appliedenergistics2:item.ItemMultiPart", damage = 440, stock = 8 },
    { label = "P2P Tunnel - ME", name = "appliedenergistics2:item.ItemMultiPart", damage = 460, stock = 8 },
    -- 	{label="Wet Concrete",is_fluid=true,name="wet.concrete",damage=0,stock=2304},
    -- 	{label="Molten Tantalum",is_fluid=true,name="molten.tantalum",damage=0,stock=144},
    -- 	{label="Fluorine",is_fluid=true,name="fluorine",damage=0,stock=4000},
    -- 	{label="2-Ethylanthrahydroquinone",is_fluid=true,name="fluid.2ethylanthrahydroquinone",damage=0,stock=1000},
    -- 	{label="Molten HSS-S",is_fluid=true,name="molten.hsss",damage=0,stock=144},
    -- 	{label="Molten HSS-G",is_fluid=true,name="molten.hssg",damage=0,stock=144},
    -- 	{label="Molten Gallium Arsenide",is_fluid=true,name="molten.galliumarsenide",damage=0,stock=288},
    -- 	{label="Sodium Formate",is_fluid=true,name="sodium formate",damage=0,stock=1000},
    -- 	{label="Hydrofluoric Acid",is_fluid=true,name="hydrofluoricacid_gt5u",damage=0,stock=2000},
    -- 	{label="Hydrochloric Acid",is_fluid=true,name="hydrochloricacid_gt5u",damage=0,stock=1000},
    -- 	{label="Molten Potassium Disulfate",is_fluid=true,name="molten.potassium disulfate",damage=0,stock=144},
    -- 	{label="Silicon Tetrachloride",is_fluid=true,name="silicontetrachloride",damage=0,stock=1000},
    -- 	{label="Iron III Chloride",is_fluid=true,name="ironiiichloride",damage=0,stock=1000},
    -- 	{label="Molten Electrum",is_fluid=true,name="molten.electrum",damage=0,stock=144},
    -- 	{label="Molten Tungstensteel",is_fluid=true,name="molten.tungstensteel",damage=0,stock=144},
    -- 	{label="Acidic Iridium Solution",is_fluid=true,name="acidic iridium solution",damage=0,stock=1000},
    -- 	{label="3,3-Dichlorobenzidine",is_fluid=true,name="3,3dichlorobenzidine",damage=0,stock=2000},
    -- 	{label="Monomethylhydrazine",is_fluid=true,name="fluid.monomethylhydrazine",damage=0,stock=1000},
    -- 	{label="Molten Rhodium-Plated Palladium",is_fluid=true,name="molten.rhodium-plated palladium",damage=0,stock=144},
    -- 	{label="Molten Bronze",is_fluid=true,name="molten.bronze",damage=0,stock=144},
    -- 	{label="Helium",is_fluid=true,name="helium",damage=0,stock=9000},
    -- 	{label="Molten Energetic Alloy",is_fluid=true,name="molten.energeticalloy",damage=0,stock=144},
    -- 	{label="Palladium Enriched Ammonia",is_fluid=true,name="palladium enriched ammonia",damage=0,stock=3600},
    -- 	{label="Oxygen",is_fluid=true,name="oxygen",damage=0,stock=4000},
    -- 	{label="Aqua Regia",is_fluid=true,name="aqua regia",damage=0,stock=4000},
    -- 	{label="Rhodium Sulfate Solution",is_fluid=true,name="rhodium sulfate solution",damage=0,stock=39600},
    -- 	{label="Lead-Zinc Solution",is_fluid=true,name="leadzincsolution",damage=0,stock=16000},
    -- 	{label="Molten Watertight Steel",is_fluid=true,name="molten.watertightsteel",damage=0,stock=2880},
    -- 	{label="Rhodium Salt Solution",is_fluid=true,name="rhodium salt solution",damage=0,stock=200},
    -- 	{label="Ammonia",is_fluid=true,name="ammonia",damage=0,stock=1000},
    -- 	{label="Hot Ruthenium Tetroxide Solution",is_fluid=true,name="hot ruthenium tetroxide solution",damage=0,stock=2000},
    -- 	{label="Molten Zeron-100",is_fluid=true,name="molten.zeron100",damage=0,stock=7200},
    -- 	{label="Formic Acid",is_fluid=true,name="formic acid",damage=0,stock=4000},
    -- 	{label="Liquid Helium",is_fluid=true,name="liquid helium",damage=0,stock=1000},
    -- 	{label="Deuterium",is_fluid=true,name="deuterium",damage=0,stock=1000},
    -- 	{label="Dichlorobenzene",is_fluid=true,name="dichlorobenzene",damage=0,stock=4000},
    -- 	{label="1,2-Dimethylbenzene",is_fluid=true,name="dimethylbenzene",damage=0,stock=2000},
    -- 	{label="Hydrogen",is_fluid=true,name="hydrogen",damage=0,stock=2000},
    -- 	{label="Sodium Tungstate",is_fluid=true,name="sodium tungstate",damage=0,stock=1000},
    -- 	{label="Molten Indalloy 140",is_fluid=true,name="molten.indalloy140",damage=0,stock=14400},
    -- 	{label="Molten Polybenzimidazole",is_fluid=true,name="molten.polybenzimidazole",damage=0,stock=1000},
    -- 	{label="Phthalic Acid",is_fluid=true,name="phtalicacid",damage=0,stock=1000},
    -- 	{label="Molten Polyphenylene Sulfide",is_fluid=true,name="molten.polyphenylenesulfide",damage=0,stock=1500},
    -- 	{label="2-Nitrochlorobenzene",is_fluid=true,name="2nitrochlorobenzene",damage=0,stock=2000},
    -- 	{label="Ruthenium Tetroxide Solution",is_fluid=true,name="ruthenium tetroxide solution",damage=0,stock=9000},
    -- 	{label="Platinum Concentrate",is_fluid=true,name="platinum concentrate",damage=0,stock=18000},
    -- 	{label="Ether",is_fluid=true,name="ether",damage=0,stock=4000},
    -- 	{label="Indium Concentrate",is_fluid=true,name="indiumconcentrate",damage=0,stock=16000},
    -- 	{label="Nitrobenzene",is_fluid=true,name="nitrobenzene",damage=0,stock=5000},
    -- 	{label="Hydrazine",is_fluid=true,name="fluid.hydrazine",damage=0,stock=1000},
    -- 	{label="Molten Platinum",is_fluid=true,name="molten.platinum",damage=0,stock=144},
    -- 	{label="Molten Naquadah",is_fluid=true,name="molten.naquadah",damage=0,stock=144},
    -- 	{label="Chlorobenzene",is_fluid=true,name="chlorobenzene",damage=0,stock=2000},
    -- 	{label="Nitrogen Dioxide",is_fluid=true,name="nitrogendioxide",damage=0,stock=1000},
    -- 	{label="Molten Ledox",is_fluid=true,name="molten.ledox",damage=0,stock=144},
    -- 	{label="Molten Steel",is_fluid=true,name="molten.steel",damage=0,stock=144},
    -- 	{label="Rhodium Filter Cake Solution",is_fluid=true,name="rhodium filter cake solution",damage=0,stock=1000},
    -- 	{label="Molten Vanadium-Gallium",is_fluid=true,name="molten.vanadiumgallium",damage=0,stock=144},
    -- 	{label="Molten Stainless Steel",is_fluid=true,name="molten.stainlesssteel",damage=0,stock=144},
    -- 	{label="Nitric Acid",is_fluid=true,name="nitricacid",damage=0,stock=2000},
    -- 	{label="2-Ethylanthraquinone",is_fluid=true,name="fluid.2ethylanthraquinone",damage=0,stock=5000},
    -- 	{label="Molten Titanium",is_fluid=true,name="molten.titanium",damage=0,stock=144},
    -- 	{label="Diphenyl Isophthalate",is_fluid=true,name="diphenylisophtalate",damage=0,stock=1000},
    -- 	{label="Tetrafluoroethylene",is_fluid=true,name="tetrafluoroethylene",damage=0,stock=1000},
    -- 	{label="Molten Soldering Alloy",is_fluid=true,name="molten.solderingalloy",damage=0,stock=144},
    -- 	{label="Dense Hydrazine Fuel Mixture",is_fluid=true,name="fluid.rocketfuelmixd",damage=0,stock=10000},
    -- 	{label="CN3H7O3 Rocket Fuel",is_fluid=true,name="fluid.rocketfuelmixc",damage=0,stock=2000},
    -- 	{label="Molten Polyvinyl Chloride",is_fluid=true,name="molten.polyvinylchloride",damage=0,stock=1500},
    -- 	{label="Blazing Pyrotheum",is_fluid=true,name="pyrotheum",damage=0,stock=250},
    -- 	{label="3,3-Diaminobenzidine",is_fluid=true,name="3,3diaminobenzidine",damage=0,stock=1000},
    -- 	{label="Molten Inconel-625",is_fluid=true,name="molten.inconel625",damage=0,stock=6192},
    -- 	{label="Ruthenium Tetroxide",is_fluid=true,name="ruthenium tetroxide",damage=0,stock=36000},
    -- 	{label="Molten Hastelloy-X",is_fluid=true,name="molten.hastelloyx",damage=0,stock=7200},
    -- 	{label="Molten Hastelloy-W",is_fluid=true,name="molten.hastelloyw",damage=0,stock=7200},
    -- 	{label="Molten Hastelloy-N",is_fluid=true,name="molten.hastelloyn",damage=0,stock=3600},
    -- 	{label="Molten Polytetrafluoroethylene",is_fluid=true,name="molten.polytetrafluoroethylene",damage=0,stock=432},
    -- 	{label="Hydrogen Peroxide",is_fluid=true,name="fluid.hydrogenperoxide",damage=0,stock=5000},
    -- 	{label="Sulfuric Acid",is_fluid=true,name="sulfuricacid",damage=0,stock=1000},
    -- 	{label="Chlorine",is_fluid=true,name="chlorine",damage=0,stock=1000},
    -- 	{label="Molten Niobium-Titanium",is_fluid=true,name="molten.niobiumtitanium",damage=0,stock=144},
    -- 	{label="Sodium Persulfate",is_fluid=true,name="sodiumpersulfate",damage=0,stock=20000},
    -- 	{label="Ammonium Chloride",is_fluid=true,name="ammonium chloride",damage=0,stock=2000},
    -- 	{label="Molten Vibrant Alloy",is_fluid=true,name="molten.vibrantalloy",damage=0,stock=144},
    -- 	{label="Molten Maraging Steel 250",is_fluid=true,name="molten.maragingsteel250",damage=0,stock=3456},
    -- 	{label="Molten Maraging Steel 300",is_fluid=true,name="molten.maragingsteel300",damage=0,stock=3456},
    -- 	{label="Vinyl Chloride",is_fluid=true,name="vinylchloride",damage=0,stock=1000},
    -- 	{label="Molten Red Steel",is_fluid=true,name="molten.redsteel",damage=0,stock=144},
    { label = "ME Dual Interface", name = "ae2fc:part_fluid_interface", damage = 0, stock = 8 },
    { label = "ME Fluid Storage Bus", name = "ae2fc:part_fluid_storage_bus", damage = 0, stock = 1 },
    -- 	{label="§e4k§r ME Fluid Storage Component",name="ae2fc:fluid_part",damage=1,stock=64},
    -- 	{label="Wand Focus: Primal",name="Thaumcraft:FocusPrimal",damage=0,stock=1},
    -- 	{label="Glass Phial",name="Thaumcraft:ItemEssence",damage=0,stock=64},
    -- 	{label="Primal Charm",name="Thaumcraft:ItemResource",damage=15,stock=1},
    -- 	{label="Primordial Pearl",name="Thaumcraft:ItemEldritchObject",damage=3,stock=1},
    -- 	{label="Fuel Bucket",name="GalacticraftCore:item.bucketFuel",damage=0,stock=1},
    -- 	{label="Oxygen Vent",name="GalacticraftCore:item.airVent",damage=0,stock=64},
    -- 	{label="Tier 1 Booster",name="GalacticraftCore:item.engine",damage=1,stock=64},
    -- 	{label="Heavy Duty Plate",name="GalacticraftCore:item.heavyPlating",damage=0,stock=64},
    -- 	{label="Canvas",name="GalacticraftCore:item.canvas",damage=0,stock=64},
    -- 	{label="Empty Canister",name="GalacticraftCore:item.oilCanisterPartial",damage=1001,stock=1},
    -- 	{label="Compressed Aluminum",name="GalacticraftCore:item.basicItem",damage=8,stock=64},
    -- 	{label="Compressed Steel",name="GalacticraftCore:item.basicItem",damage=9,stock=64},
    -- 	{label="Compressed Bronze",name="GalacticraftCore:item.basicItem",damage=10,stock=64},
    -- 	{label="Compressed Meteoric Iron",name="GalacticraftCore:item.meteoricIronIngot",damage=1,stock=64},
    -- 	{label="Parachute",name="GalacticraftCore:item.parachute",damage=0,stock=1},
    -- 	{label="Heavy Duty Plate",name="GalacticraftMars:item.itemBasicAsteroids",damage=0,stock=64},
    -- 	{label="Compressed Titanium",name="GalacticraftMars:item.itemBasicAsteroids",damage=6,stock=64},
    -- 	{label="Heavy Duty Plate",name="GalacticraftMars:item.null",damage=3,stock=64},
    -- 	{label="Compressed Desh",name="GalacticraftMars:item.null",damage=5,stock=64},
    -- 	{label="Standard Binding Agent",name="AWWayofTime:standardBindingAgent",damage=0,stock=64},
    -- 	{label="Incendium",name="AWWayofTime:incendium",damage=0,stock=64},
    -- 	{label="Magicales",name="AWWayofTime:magicales",damage=0,stock=64},
    -- 	{label="Sanctus",name="AWWayofTime:sanctus",damage=0,stock=64},
    -- 	{label="Aether",name="AWWayofTime:aether",damage=0,stock=64},
    { label = "Simple Catalyst", name = "AWWayofTime:simpleCatalyst", damage = 0, stock = 16 },
    -- 	{label="Crepitous",name="AWWayofTime:crepitous",damage=0,stock=64},
    -- 	{label="Crystallos",name="AWWayofTime:crystallos",damage=0,stock=64},
    -- 	{label="Terrae",name="AWWayofTime:terrae",damage=0,stock=64},
    -- 	{label="Aquasalus",name="AWWayofTime:aquasalus",damage=0,stock=64},
    -- 	{label="Tenebrae",name="AWWayofTime:tennebrae",damage=0,stock=64},
    -- 	{label="Weak Binding Agent",name="AWWayofTime:weakBindingAgent",damage=0,stock=64},
    -- 	{label="Cracked Runic Plate",name="AWWayofTime:bloodMagicBaseItems",damage=15,stock=64},
    -- 	{label="Offensa",name="AWWayofTime:bloodMagicBaseAlchemyItems",damage=0,stock=64},
    { label = "Strengthened Catalyst", name = "AWWayofTime:bloodMagicBaseAlchemyItems", damage = 3, stock = 8 },
    -- 	{label="Potentia",name="AWWayofTime:bloodMagicBaseAlchemyItems",damage=8,stock=64},
    -- 	{label="Mud Ball",name="BiomesOPlenty:mudball",damage=0,stock=64},
    -- 	{label="Enhanced Circuit Board",name="Forestry:chipsets",damage=1,stock=64},
    -- 	{label="Bronze Electron Tube",name="Forestry:thermionicTubes",damage=2,stock=64},
    -- 	{label="Golden Electron Tube",name="Forestry:thermionicTubes",damage=4,stock=64},
    -- 	{label="Emerald Electron Tube",name="Forestry:thermionicTubes",damage=9,stock=64},
    -- 	{label="Apatine Electron Tube",name="Forestry:thermionicTubes",damage=10,stock=64},
    -- 	{label="Ender Electron Tube",name="Forestry:thermionicTubes",damage=12,stock=64},
    -- 	{label="Ethanol Bucket",name="Forestry:bucketEthanol",damage=0,stock=1},
    -- 	{label="Item Conduit",name="EnderIO:itemItemConduit",damage=0,stock=64},
    -- 	{label="Basic Item Filter",name="EnderIO:itemBasicFilterUpgrade",damage=0,stock=64},
    -- 	{label="Octadic Capacitor",name="EnderIO:itemBasicCapacitor",damage=2,stock=64},
    -- 	{label="Machine Chassis",name="EnderIO:itemMachinePart",damage=0,stock=64},
    -- 	{label="Raw \"SDHC-120\" Alloy",name="dreamcraft:item.RawSDHCAlloy",damage=0,stock=64},
    -- 	{label="Medium Fuel Canister",name="dreamcraft:item.MediumFuelCanister",damage=0,stock=64},
    -- 	{label="Item Circuit Tier II",name="dreamcraft:item.DiamondCoreChip",damage=0,stock=64},
    -- 	{label="Compressed Ledox Plate",name="dreamcraft:item.LedoxCompressedPlate",damage=0,stock=64},
    -- 	{label="Alumino Silicate Wool",name="dreamcraft:item.AluminoSilicateWool",damage=0,stock=64},
    -- 	{label="Iridium Alloy Item Casing",name="dreamcraft:item.IridiumAlloyItemCasing",damage=0,stock=64},
    -- 	{label="SAVAGAY1",name="dreamcraft:item.IceCompressedPlate",damage=0,stock=64},
    -- 	{label="Compressed Ice Plate",name="dreamcraft:item.IceCompressedPlate",damage=0,stock=64},
    -- 	{label="Item Circuit Tier III",name="dreamcraft:item.EmeraldAdvancedCoreChip",damage=0,stock=64},
    -- 	{label="Compressed Dual Titanium Plates",name="dreamcraft:item.TitaniumDualCompressedPlates",damage=0,stock=64},
    -- 	{label="Fluid Processor Tier I",name="dreamcraft:item.EngineeringProcessorFluidDiamondCore",damage=0,stock=64},
    -- 	{label="Stainless Steel Bars",name="dreamcraft:item.StainlessSteelBars",damage=0,stock=64},
    -- 	{label="Mica Insulator Sheet",name="dreamcraft:item.MicaInsulatorSheet",damage=0,stock=64},
    -- 	{label="Quantum Crystal",name="dreamcraft:item.QuantumCrystal",damage=0,stock=64},
    -- 	{label="Essentia Processor Tier I",name="dreamcraft:item.EngineeringProcessorEssentiaPulsatingCore",damage=0,stock=64},
    -- 	{label="Mica Based Sheet",name="dreamcraft:item.MicaBasedSheet",damage=0,stock=64},
    -- 	{label="Fluid Circuit Tier I",name="dreamcraft:item.DiamondFluidCoreChip",damage=0,stock=64},
    -- 	{label="Heavy Duty Alloy Ingot T4",name="dreamcraft:item.HeavyDutyAlloyIngotT4",damage=0,stock=64},
    -- 	{label="60K Cell",name="dreamcraft:item.SixtyKCell",damage=0,stock=64},
    -- 	{label="Engraved Energy Chip",name="dreamcraft:item.EngravedEnergyChip",damage=0,stock=64},
    -- 	{label="Compressed Quantium Plate",name="dreamcraft:item.QuantinumCompressedPlate",damage=0,stock=64},
    -- 	{label="30K Cell",name="dreamcraft:item.ThirtyKCell",damage=0,stock=64},
    -- 	{label="Item Processor Tier I",name="dreamcraft:item.LogicProcessorItemGoldCore",damage=0,stock=64},
    -- 	{label="Compressed Dual Desh Plates",name="dreamcraft:item.DeshDualCompressedPlates",damage=0,stock=64},
    -- 	{label="Mica Based Pulp",name="dreamcraft:item.MicaBasedPulp",damage=0,stock=64},
    -- 	{label="Compressed Callisto Ice Plate",name="dreamcraft:item.CallistoIceCompressedPlate",damage=0,stock=64},
    -- 	{label="Raw Lapotron Crystal",name="dreamcraft:item.RawLapotronCrystal",damage=0,stock=64},
    -- 	{label="Item Processor Tier II",name="dreamcraft:item.EngineeringProcessorItemDiamondCore",damage=0,stock=64},
    -- 	{label="Lapotron Dust",name="dreamcraft:item.LapotronDust",damage=0,stock=64},
    -- 	{label="10K Cell",name="dreamcraft:item.TenKCell",damage=0,stock=64},
    -- 	{label="Etched Low Voltage Wiring",name="dreamcraft:item.EtchedLowVoltageWiring",damage=0,stock=64},
    -- 	{label="Mica Insulator Foil",name="dreamcraft:item.MicaInsulatorFoil",damage=0,stock=64},
    -- 	{label="Engraved Diamond Crystal Chip",name="dreamcraft:item.EngravedDiamondCrystalChip",damage=0,stock=64},
    -- 	{label="Essentia Circuit",name="dreamcraft:item.EssentiaCircuit",damage=0,stock=64},
    -- 	{label="Item Processor Tier III",name="dreamcraft:item.EngineeringProcessorItemEmeraldCore",damage=0,stock=64},
    -- 	{label="Charged Certus Quartz Dust",name="dreamcraft:item.ChargedCertusQuartzDust",damage=0,stock=64},
    -- 	{label="Heavy Duty Plate Tier 4",name="dreamcraft:item.HeavyDutyPlateTier4",damage=0,stock=64},
    -- 	{label="Heavy Duty Plate Tier 5",name="dreamcraft:item.HeavyDutyPlateTier5",damage=0,stock=64},
    -- 	{label="Bucket of Nitric Acid",name="dreamcraft:dreamcraft_NitricAcid_bucket",damage=0,stock=1},
    -- 	{label="Rune of Water",name="Botania:rune",damage=0,stock=64},
    -- 	{label="Rune of Fire",name="Botania:rune",damage=1,stock=64},
    -- 	{label="Rune of Earth",name="Botania:rune",damage=2,stock=64},
    -- 	{label="Rune of Air",name="Botania:rune",damage=3,stock=64},
    -- 	{label="Rune of Spring",name="Botania:rune",damage=4,stock=64},
    -- 	{label="Rune of Summer",name="Botania:rune",damage=5,stock=64},
    -- 	{label="Rune of Autumn",name="Botania:rune",damage=6,stock=64},
    -- 	{label="Rune of Winter",name="Botania:rune",damage=7,stock=64},
    -- 	{label="Rune of Mana",name="Botania:rune",damage=8,stock=64},
    -- 	{label="Rune of Lust",name="Botania:rune",damage=9,stock=64},
    -- 	{label="Rune of Gluttony",name="Botania:rune",damage=10,stock=64},
    -- 	{label="Rune of Greed",name="Botania:rune",damage=11,stock=64},
    -- 	{label="Rune of Sloth",name="Botania:rune",damage=12,stock=64},
    -- 	{label="Rune of Wrath",name="Botania:rune",damage=13,stock=64},
    -- 	{label="Rune of Envy",name="Botania:rune",damage=14,stock=64},
    -- 	{label="Rune of Pride",name="Botania:rune",damage=15,stock=64},
    -- 	{label="Tanned Leather",name="Backpack:tannedLeather",damage=0,stock=64},
    -- 	{label="Redstone Chipset",name="BuildCraft|Silicon:redstoneChipset",damage=0,stock=64},
    -- 	{label="Diamond Chipset",name="BuildCraft|Silicon:redstoneChipset",damage=3,stock=64},
    -- 	{label="Pulsating Chipset",name="BuildCraft|Silicon:redstoneChipset",damage=4,stock=64},
    -- 	{label="Emerald Chipset",name="BuildCraft|Silicon:redstoneChipset",damage=7,stock=64},
    -- 	{label="Woven Cotton",name="harvestcraft:wovencottonItem",damage=0,stock=64},
    -- 	{label="Hardened Leather",name="harvestcraft:hardenedleatherItem",damage=0,stock=64},
    -- 	{label="Tiny Pile of Indium Dust",name="gregtech:gt.metaitem.01",damage=56,stock=64},
    -- 	{label="Tiny Pile of Europium Dust",name="gregtech:gt.metaitem.01",damage=70,stock=64},
    -- 	{label="Tiny Pile of Platinum Dust",name="gregtech:gt.metaitem.01",damage=85,stock=64},
    -- 	{label="Tiny Pile of Stainless Steel Dust",name="gregtech:gt.metaitem.01",damage=306,stock=64},
    -- 	{label="Tiny Pile of Tungstensteel Dust",name="gregtech:gt.metaitem.01",damage=316,stock=64},
    -- 	{label="Tiny Pile of Ashes",name="gregtech:gt.metaitem.01",damage=815,stock=64},
    -- 	{label="Tiny Pile of Dark Ashes",name="gregtech:gt.metaitem.01",damage=816,stock=64},
    -- 	{label="Lithium Dust",name="gregtech:gt.metaitem.01",damage=2006,stock=64},
    -- 	{label="Sodium Dust",name="gregtech:gt.metaitem.01",damage=2017,stock=64},
    -- 	{label="Magnesium Dust",name="gregtech:gt.metaitem.01",damage=2018,stock=64},
    -- 	{label="Raw Silicon Dust",name="gregtech:gt.metaitem.01",damage=2020,stock=64},
    -- 	{label="Sulfur Dust",name="gregtech:gt.metaitem.01",damage=2022,stock=64},
    -- 	{label="Titanium Dust",name="gregtech:gt.metaitem.01",damage=2028,stock=64},
    -- 	{label="Iron Dust",name="gregtech:gt.metaitem.01",damage=2032,stock=64},
    -- 	{label="Palladium Dust",name="gregtech:gt.metaitem.01",damage=2052,stock=64},
    -- 	{label="Indium Dust",name="gregtech:gt.metaitem.01",damage=2056,stock=64},
    -- 	{label="Barium Dust",name="gregtech:gt.metaitem.01",damage=2063,stock=64},
    -- 	{label="Samarium Dust",name="gregtech:gt.metaitem.01",damage=2069,stock=64},
    -- 	{label="Tungsten Dust",name="gregtech:gt.metaitem.01",damage=2081,stock=64},
    -- 	{label="Osmium Dust",name="gregtech:gt.metaitem.01",damage=2083,stock=64},
    -- 	{label="Iridium Dust",name="gregtech:gt.metaitem.01",damage=2084,stock=64},
    -- 	{label="Platinum Dust",name="gregtech:gt.metaitem.01",damage=2085,stock=64},
    -- 	{label="Bronze Dust",name="gregtech:gt.metaitem.01",damage=2300,stock=64},
    -- 	{label="Brass Dust",name="gregtech:gt.metaitem.01",damage=2301,stock=64},
    -- 	{label="Electrum Dust",name="gregtech:gt.metaitem.01",damage=2303,stock=64},
    -- 	{label="Steel Dust",name="gregtech:gt.metaitem.01",damage=2305,stock=64},
    -- 	{label="Stainless Steel Dust",name="gregtech:gt.metaitem.01",damage=2306,stock=64},
    -- 	{label="Red Alloy Dust",name="gregtech:gt.metaitem.01",damage=2308,stock=64},
    -- 	{label="Nichrome Dust",name="gregtech:gt.metaitem.01",damage=2311,stock=64},
    -- 	{label="Magnalium Dust",name="gregtech:gt.metaitem.01",damage=2313,stock=64},
    -- 	{label="Soldering Alloy Dust",name="gregtech:gt.metaitem.01",damage=2314,stock=64},
    -- 	{label="Tungstensteel Dust",name="gregtech:gt.metaitem.01",damage=2316,stock=64},
    -- 	{label="Osmiridium Dust",name="gregtech:gt.metaitem.01",damage=2317,stock=64},
    -- 	{label="Enderium Dust",name="gregtech:gt.metaitem.01",damage=2321,stock=64},
    -- 	{label="Black Steel Dust",name="gregtech:gt.metaitem.01",damage=2334,stock=64},
    -- 	{label="Red Steel Dust",name="gregtech:gt.metaitem.01",damage=2348,stock=64},
    -- 	{label="Blue Steel Dust",name="gregtech:gt.metaitem.01",damage=2349,stock=64},
    -- 	{label="Sterling Silver Dust",name="gregtech:gt.metaitem.01",damage=2350,stock=64},
    -- 	{label="Rose Gold Dust",name="gregtech:gt.metaitem.01",damage=2351,stock=64},
    -- 	{label="Black Bronze Dust",name="gregtech:gt.metaitem.01",damage=2352,stock=64},
    -- 	{label="Bismuth Bronze Dust",name="gregtech:gt.metaitem.01",damage=2353,stock=64},
    -- 	{label="Vanadium-Gallium Dust",name="gregtech:gt.metaitem.01",damage=2357,stock=64},
    -- 	{label="Yttrium Barium Cuprate Dust",name="gregtech:gt.metaitem.01",damage=2358,stock=64},
    -- 	{label="Niobium-Titanium Dust",name="gregtech:gt.metaitem.01",damage=2360,stock=64},
    -- 	{label="Chromium Dioxide Dust",name="gregtech:gt.metaitem.01",damage=2361,stock=64},
    -- 	{label="Dark Steel Dust",name="gregtech:gt.metaitem.01",damage=2364,stock=64},
    -- 	{label="Electrical Steel Dust",name="gregtech:gt.metaitem.01",damage=2365,stock=64},
    { label = "Energetic Alloy Dust", name = "gregtech:gt.metaitem.01", damage = 2366, stock = 64 },
    -- 	{label="Vibrant Alloy Dust",name="gregtech:gt.metaitem.01",damage=2367,stock=64},
    -- 	{label="Conductive Iron Dust",name="gregtech:gt.metaitem.01",damage=2369,stock=64},
    -- 	{label="HSS-G Dust",name="gregtech:gt.metaitem.01",damage=2372,stock=64},
    -- 	{label="HSS-S Dust",name="gregtech:gt.metaitem.01",damage=2374,stock=64},
    -- 	{label="Rutile Dust",name="gregtech:gt.metaitem.01",damage=2375,stock=64},
    -- 	{label="Pulsating Iron Dust",name="gregtech:gt.metaitem.01",damage=2378,stock=64},
    -- 	{label="Enderium Base Dust",name="gregtech:gt.metaitem.01",damage=2380,stock=64},
    -- 	{label="Redstone Alloy Dust",name="gregtech:gt.metaitem.01",damage=2381,stock=64},
    -- 	{label="Duralumin Dust",name="gregtech:gt.metaitem.01",damage=2392,stock=64},
    -- 	{label="End Steel Dust",name="gregtech:gt.metaitem.01",damage=2401,stock=64},
    -- 	{label="Tricalcium Phosphate Dust",name="gregtech:gt.metaitem.01",damage=2534,stock=64},
    -- 	{label="TPV-Alloy Dust",name="gregtech:gt.metaitem.01",damage=2576,stock=64},
    -- 	{label="Chromium Trioxide Dust",name="gregtech:gt.metaitem.01",damage=2591,stock=64},
    -- 	{label="Potassium Dichromate Dust",name="gregtech:gt.metaitem.01",damage=2594,stock=64},
    -- 	{label="Potassium Dichromate Dust",name="gregtech:gt.metaitem.01",damage=2594,stock=64},
    -- 	{label="Magnesia Dust",name="gregtech:gt.metaitem.01",damage=2621,stock=64},
    -- 	{label="Sodium Bisulfate Dust",name="gregtech:gt.metaitem.01",damage=2630,stock=64},
    -- 	{label="Sodium Hydroxide Dust",name="gregtech:gt.metaitem.01",damage=2685,stock=64},
    -- 	{label="Sodium Sulfide Dust",name="gregtech:gt.metaitem.01",damage=2719,stock=64},
    -- 	{label="Clay Dust",name="gregtech:gt.metaitem.01",damage=2805,stock=64},
    { label = "Graphene Dust", name = "gregtech:gt.metaitem.01", damage = 2819, stock = 1024 },
    -- 	{label="Pyrotheum Dust",name="gregtech:gt.metaitem.01",damage=2843,stock=64},
     	{label="Silicon Solar Grade (Poly SI) Dust",name="gregtech:gt.metaitem.01",damage=2856,stock=256},
    -- 	{label="Polyethylene Pulp",name="gregtech:gt.metaitem.01",damage=2874,stock=64},
    -- 	{label="Glass Dust",name="gregtech:gt.metaitem.01",damage=2890,stock=64},
    -- 	{label="Scheelite Dust",name="gregtech:gt.metaitem.01",damage=2910,stock=64},
    -- 	{label="Indium Gallium Phosphide Dust",name="gregtech:gt.metaitem.01",damage=2981,stock=64},
    -- 	{label="Superconductor Base IV Dust",name="gregtech:gt.metaitem.01",damage=2990,stock=64},
    -- 	{label="Superconductor Base LuV Dust",name="gregtech:gt.metaitem.01",damage=2991,stock=64},
    -- 	{label="Purified Titanium Ore",name="gregtech:gt.metaitem.01",damage=6028,stock=64},
    -- 	{label="Purified Nether Star Ore",name="gregtech:gt.metaitem.01",damage=6506,stock=64},
    -- 	{label="Naquadah Nugget",name="gregtech:gt.metaitem.01",damage=9324,stock=64},
    { label = "Aluminium Ingot", name = "gregtech:gt.metaitem.01", damage = 11019, stock = 512 },
    { label = "Titanium Ingot", name = "gregtech:gt.metaitem.01", damage = 11028, stock = 512 },
    -- 	{label="Cobalt Ingot",name="gregtech:gt.metaitem.01",damage=11033,stock=64},
    -- 	{label="Nickel Ingot",name="gregtech:gt.metaitem.01",damage=11034,stock=64},
    -- 	{label="Copper Ingot",name="gregtech:gt.metaitem.01",damage=11035,stock=64},
    -- 	{label="Palladium Ingot",name="gregtech:gt.metaitem.01",damage=11052,stock=64},
    -- 	{label="Silver Ingot",name="gregtech:gt.metaitem.01",damage=11054,stock=64},
    { label = "Tin Ingot", name = "gregtech:gt.metaitem.01", damage = 11057, stock = 256 },
    -- 	{label="Neodymium Ingot",name="gregtech:gt.metaitem.01",damage=11067,stock=64},
    -- 	{label="Samarium Ingot",name="gregtech:gt.metaitem.01",damage=11069,stock=64},
    { label = "Tantalum Ingot", name = "gregtech:gt.metaitem.01", damage = 11080, stock = 512 },
    { label = "Tungsten Ingot", name = "gregtech:gt.metaitem.01", damage = 11081, stock = 512 },
    -- 	{label="Osmium Ingot",name="gregtech:gt.metaitem.01",damage=11083,stock=64},
    { label = "Iridium Ingot", name = "gregtech:gt.metaitem.01", damage = 11084, stock = 64 },
    { label = "Platinum Ingot", name = "gregtech:gt.metaitem.01", damage = 11085, stock = 512 },
    -- 	{label="Bronze Ingot",name="gregtech:gt.metaitem.01",damage=11300,stock=64},
    -- 	{label="Invar Ingot",name="gregtech:gt.metaitem.01",damage=11302,stock=64},
    -- 	{label="Electrum Ingot",name="gregtech:gt.metaitem.01",damage=11303,stock=64},
    -- 	{label="Wrought Iron Ingot",name="gregtech:gt.metaitem.01",damage=11304,stock=64},
    { label = "Steel Ingot", name = "gregtech:gt.metaitem.01", damage = 11305, stock = 1024 },
    { label = "Stainless Steel Ingot", name = "gregtech:gt.metaitem.01", damage = 11306, stock = 1024 },
    -- 	{label="Blue Alloy Ingot",name="gregtech:gt.metaitem.01",damage=11309,stock=64},
    -- 	{label="Cupronickel Ingot",name="gregtech:gt.metaitem.01",damage=11310,stock=64},
    -- 	{label="Nichrome Ingot",name="gregtech:gt.metaitem.01",damage=11311,stock=64},
    { label = "Tungstensteel Ingot", name = "gregtech:gt.metaitem.01", damage = 11316, stock = 512 },
    -- 	{label="Osmiridium Ingot",name="gregtech:gt.metaitem.01",damage=11317,stock=64},
    -- 	{label="Enderium Ingot",name="gregtech:gt.metaitem.01",damage=11321,stock=64},
    { label = "Naquadah Ingot", name = "gregtech:gt.metaitem.01", damage = 11324, stock = 64 },
    { label = "Mithril Ingot", name = "gregtech:gt.metaitem.01", damage = 11331, stock = 128 },
    { label = "Black Steel Ingot", name = "gregtech:gt.metaitem.01", damage = 11334, stock = 128 },
    -- 	{label="Meteoric Iron Ingot",name="gregtech:gt.metaitem.01",damage=11340,stock=64},
    -- 	{label="Meteoric Steel Ingot",name="gregtech:gt.metaitem.01",damage=11341,stock=64},
     	{label="Annealed Copper Ingot",name="gregtech:gt.metaitem.01",damage=11345,stock=512},
    -- 	{label="Red Steel Ingot",name="gregtech:gt.metaitem.01",damage=11348,stock=64},
    -- 	{label="Blue Steel Ingot",name="gregtech:gt.metaitem.01",damage=11349,stock=64},
    -- 	{label="Vanadium-Gallium Ingot",name="gregtech:gt.metaitem.01",damage=11357,stock=64},
    { label = "Yttrium Barium Cuprate Ingot", name = "gregtech:gt.metaitem.01", damage = 11358, stock = 64 },
     	{label="Niobium-Titanium Ingot",name="gregtech:gt.metaitem.01",damage=11360,stock=64},
    { label = "Energetic Alloy Ingot", name = "gregtech:gt.metaitem.01", damage = 11366, stock = 256 },
    -- 	{label="Vibrant Alloy Ingot",name="gregtech:gt.metaitem.01",damage=11367,stock=64},
    -- 	{label="HSS-G Ingot",name="gregtech:gt.metaitem.01",damage=11372,stock=64},
    { label = "HSS-S Ingot", name = "gregtech:gt.metaitem.01", damage = 11374, stock = 64 },
    -- 	{label="Pulsating Iron Ingot",name="gregtech:gt.metaitem.01",damage=11378,stock=64},
    -- 	{label="Callisto Ice Ingot",name="gregtech:gt.metaitem.01",damage=11389,stock=64},
    -- 	{label="Ledox Ingot",name="gregtech:gt.metaitem.01",damage=11390,stock=64},
    -- 	{label="Quantium Ingot",name="gregtech:gt.metaitem.01",damage=11391,stock=64},
    -- 	{label="Duralumin Ingot",name="gregtech:gt.metaitem.01",damage=11392,stock=64},
    -- 	{label="Oriharukon Ingot",name="gregtech:gt.metaitem.01",damage=11393,stock=64},
    -- 	{label="End Steel Ingot",name="gregtech:gt.metaitem.01",damage=11401,stock=64},
    -- 	{label="Polytetrafluoroethylene Bar",name="gregtech:gt.metaitem.01",damage=11473,stock=64},
    -- 	{label="Polyphenylene Sulfide Ingot",name="gregtech:gt.metaitem.01",damage=11631,stock=64},
    -- 	{label="Polyvinyl Chloride Bar",name="gregtech:gt.metaitem.01",damage=11649,stock=64},
    -- 	{label="Silicon Solar Grade (Poly SI) Ingot",name="gregtech:gt.metaitem.01",damage=11856,stock=64},
    -- 	{label="Polyethylene Bar",name="gregtech:gt.metaitem.01",damage=11874,stock=64},
    -- 	{label="Desh Ingot",name="gregtech:gt.metaitem.01",damage=11884,stock=64},
    -- 	{label="Ichorium Ingot",name="gregtech:gt.metaitem.01",damage=11978,stock=64},
    -- 	{label="Superconductor Base IV Ingot",name="gregtech:gt.metaitem.01",damage=11990,stock=64},
    -- 	{label="Superconductor Base LuV Ingot",name="gregtech:gt.metaitem.01",damage=11991,stock=64},
    { label = "Aluminium Plate", name = "gregtech:gt.metaitem.01", damage = 17019, stock = 256 },
    { label = "Titanium Plate", name = "gregtech:gt.metaitem.01", damage = 17028, stock = 128 },
    { label = "Iron Plate", name = "gregtech:gt.metaitem.01", damage = 17032, stock = 64 },
    -- 	{label="Copper Plate",name="gregtech:gt.metaitem.01",damage=17035,stock=64},
    -- 	{label="Silver Plate",name="gregtech:gt.metaitem.01",damage=17054,stock=64},
    -- 	{label="Tin Plate",name="gregtech:gt.metaitem.01",damage=17057,stock=64},
    -- 	{label="Platinum Plate",name="gregtech:gt.metaitem.01",damage=17085,stock=64},
    -- 	{label="Gold Plate",name="gregtech:gt.metaitem.01",damage=17086,stock=64},
    -- 	{label="Bronze Plate",name="gregtech:gt.metaitem.01",damage=17300,stock=64},
    -- 	{label="Invar Plate",name="gregtech:gt.metaitem.01",damage=17302,stock=64},
    -- 	{label="Wrought Iron Plate",name="gregtech:gt.metaitem.01",damage=17304,stock=64},
    { label = "Steel Plate", name = "gregtech:gt.metaitem.01", damage = 17305, stock = 64 },
    { label = "Stainless Steel Plate", name = "gregtech:gt.metaitem.01", damage = 17306, stock = 64 },
    -- 	{label="Tungstensteel Plate",name="gregtech:gt.metaitem.01",damage=17316,stock=64},
    -- 	{label="Meteoric Iron Plate",name="gregtech:gt.metaitem.01",damage=17340,stock=64},
    -- 	{label="HSS-S Plate",name="gregtech:gt.metaitem.01",damage=17374,stock=64},
    -- 	{label="Pulsating Iron Plate",name="gregtech:gt.metaitem.01",damage=17378,stock=64},
    -- 	{label="Silicone Rubber Sheet",name="gregtech:gt.metaitem.01",damage=17471,stock=64},
    -- 	{label="Polytetrafluoroethylene Sheet",name="gregtech:gt.metaitem.01",damage=17473,stock=64},
    { label = "Diamond Plate", name = "gregtech:gt.metaitem.01", damage = 17500, stock = 32 },
    -- 	{label="Emerald Plate",name="gregtech:gt.metaitem.01",damage=17501,stock=64},
    -- 	{label="Fiber-Reinforced Epoxy Resin Sheet",name="gregtech:gt.metaitem.01",damage=17610,stock=64},
    -- 	{label="Polyvinyl Chloride Sheet",name="gregtech:gt.metaitem.01",damage=17649,stock=64},
    -- 	{label="Redstone Plate",name="gregtech:gt.metaitem.01",damage=17810,stock=64},
    -- 	{label="Glowstone Plate",name="gregtech:gt.metaitem.01",damage=17811,stock=64},
    -- 	{label="Silicon Solar Grade (Poly SI) Plate",name="gregtech:gt.metaitem.01",damage=17856,stock=64},
    -- 	{label="Desh Plate",name="gregtech:gt.metaitem.01",damage=17884,stock=64},
    -- 	{label="Double Iron Plate",name="gregtech:gt.metaitem.01",damage=18032,stock=64},
    -- 	{label="Double Gold Plate",name="gregtech:gt.metaitem.01",damage=18086,stock=64},
    -- 	{label="Double Steel Plate",name="gregtech:gt.metaitem.01",damage=18305,stock=64},
    -- 	{label="Double Stainless Steel Plate",name="gregtech:gt.metaitem.01",damage=18306,stock=64},
    -- 	{label="Double Niobium-Titanium Plate",name="gregtech:gt.metaitem.01",damage=18360,stock=64},
    -- 	{label="Triple Aluminium Plate",name="gregtech:gt.metaitem.01",damage=19019,stock=64},
    -- 	{label="Triple Titanium Plate",name="gregtech:gt.metaitem.01",damage=19028,stock=64},
    -- 	{label="Triple Nickel Plate",name="gregtech:gt.metaitem.01",damage=19034,stock=64},
    -- 	{label="Triple Iridium Plate",name="gregtech:gt.metaitem.01",damage=19084,stock=64},
    -- 	{label="Triple Lead Plate",name="gregtech:gt.metaitem.01",damage=19089,stock=64},
    -- 	{label="Triple Bronze Plate",name="gregtech:gt.metaitem.01",damage=19300,stock=64},
    -- 	{label="Triple Steel Plate",name="gregtech:gt.metaitem.01",damage=19305,stock=64},
    -- 	{label="Triple Tungstensteel Plate",name="gregtech:gt.metaitem.01",damage=19316,stock=64},
    -- 	{label="Triple Mithril Plate",name="gregtech:gt.metaitem.01",damage=19331,stock=64},
    -- 	{label="Triple Meteoric Iron Plate",name="gregtech:gt.metaitem.01",damage=19340,stock=64},
    -- 	{label="Triple Callisto Ice Plate",name="gregtech:gt.metaitem.01",damage=19389,stock=64},
    -- 	{label="Triple Ledox Plate",name="gregtech:gt.metaitem.01",damage=19390,stock=64},
    -- 	{label="Triple Quantium Plate",name="gregtech:gt.metaitem.01",damage=19391,stock=64},
    -- 	{label="Triple Duralumin Plate",name="gregtech:gt.metaitem.01",damage=19392,stock=64},
    -- 	{label="Triple Desh Plate",name="gregtech:gt.metaitem.01",damage=19884,stock=64},
    { label = "Aluminium Rod", name = "gregtech:gt.metaitem.01", damage = 23019, stock = 64 },
    { label = "Titanium Rod", name = "gregtech:gt.metaitem.01", damage = 23028, stock = 32 },
    -- 	{label="Chrome Rod",name="gregtech:gt.metaitem.01",damage=23030,stock=64},
    { label = "Iron Rod", name = "gregtech:gt.metaitem.01", damage = 23032, stock = 64 },
    -- 	{label="Neodymium Rod",name="gregtech:gt.metaitem.01",damage=23067,stock=64},
    -- 	{label="Samarium Rod",name="gregtech:gt.metaitem.01",damage=23069,stock=64},
    -- 	{label="Iridium Rod",name="gregtech:gt.metaitem.01",damage=23084,stock=64},
    -- 	{label="Platinum Rod",name="gregtech:gt.metaitem.01",damage=23085,stock=64},
    -- 	{label="Invar Rod",name="gregtech:gt.metaitem.01",damage=23302,stock=64},
    { label = "Steel Rod", name = "gregtech:gt.metaitem.01", damage = 23305, stock = 128 },
    { label = "Stainless Steel Rod", name = "gregtech:gt.metaitem.01", damage = 23306, stock = 64 },
    -- 	{label="Tungstensteel Rod",name="gregtech:gt.metaitem.01",damage=23316,stock=64},
    -- 	{label="Meteoric Iron Rod",name="gregtech:gt.metaitem.01",damage=23340,stock=64},
    -- 	{label="Magnetic Iron Rod",name="gregtech:gt.metaitem.01",damage=23354,stock=64},
    -- 	{label="Magnetic Steel Rod",name="gregtech:gt.metaitem.01",damage=23355,stock=64},
    -- 	{label="Magnetic Neodymium Rod",name="gregtech:gt.metaitem.01",damage=23356,stock=64},
    -- 	{label="HSS-S Rod",name="gregtech:gt.metaitem.01",damage=23374,stock=64},
    -- 	{label="Magnetic Samarium Rod",name="gregtech:gt.metaitem.01",damage=23399,stock=64},
    -- 	{label="Polytetrafluoroethylene Rod",name="gregtech:gt.metaitem.01",damage=23473,stock=64},
    -- 	{label="Polyethylene Rod",name="gregtech:gt.metaitem.01",damage=23874,stock=64},
    -- 	{label="HSS-S Round",name="gregtech:gt.metaitem.01",damage=25374,stock=64},
    -- 	{label="Stainless Steel Screw",name="gregtech:gt.metaitem.01",damage=27306,stock=64},
    -- 	{label="Tungstensteel Screw",name="gregtech:gt.metaitem.01",damage=27316,stock=64},
    -- 	{label="HSS-S Screw",name="gregtech:gt.metaitem.01",damage=27374,stock=64},
    -- 	{label="Iron Ring",name="gregtech:gt.metaitem.01",damage=28032,stock=64},
    -- 	{label="Bronze Ring",name="gregtech:gt.metaitem.01",damage=28300,stock=64},
    -- 	{label="Steel Ring",name="gregtech:gt.metaitem.01",damage=28305,stock=64},
    -- 	{label="HSS-S Ring",name="gregtech:gt.metaitem.01",damage=28374,stock=64},
    -- 	{label="Silicone Rubber Ring",name="gregtech:gt.metaitem.01",damage=28471,stock=64},
    -- 	{label="Aluminium Foil",name="gregtech:gt.metaitem.01",damage=29019,stock=64},
    -- 	{label="Copper Foil",name="gregtech:gt.metaitem.01",damage=29035,stock=64},
    -- 	{label="Gallium Foil",name="gregtech:gt.metaitem.01",damage=29037,stock=64},
    -- 	{label="Tantalum Foil",name="gregtech:gt.metaitem.01",damage=29080,stock=64},
    -- 	{label="Gold Foil",name="gregtech:gt.metaitem.01",damage=29086,stock=64},
    -- 	{label="Electrum Foil",name="gregtech:gt.metaitem.01",damage=29303,stock=64},
    -- 	{label="Energetic Alloy Foil",name="gregtech:gt.metaitem.01",damage=29366,stock=64},
    -- 	{label="Polyphenylene Sulfide Foil",name="gregtech:gt.metaitem.01",damage=29631,stock=64},
    -- 	{label="Thin Polyvinyl Chloride Sheet",name="gregtech:gt.metaitem.01",damage=29649,stock=64},
    -- 	{label="NAND Chip Array",name="gregtech:gt.metaitem.01",damage=32081,stock=64},
    -- 	{label="Large Steel Fluid Cell",name="gregtech:gt.metaitem.01",damage=32405,stock=64},
    -- 	{label="Heavy Duty Alloy Ingot T1",name="gregtech:gt.metaitem.01",damage=32462,stock=64},
    -- 	{label="Heavy Duty Alloy Ingot T2",name="gregtech:gt.metaitem.01",damage=32463,stock=64},
    -- 	{label="Heavy Duty Alloy Ingot T3",name="gregtech:gt.metaitem.01",damage=32464,stock=64},
    -- 	{label="Large Battery Hull",name="gregtech:gt.metaitem.01",damage=32502,stock=64},
    -- 	{label="Large Lithium Battery",name="gregtech:gt.metaitem.01",damage=32538,stock=64},
    -- 	{label="Lapotronic Energy Orb",name="gregtech:gt.metaitem.01",damage=32597,stock=64},
    { label = "Electric Motor (LV)", name = "gregtech:gt.metaitem.01", damage = 32600, stock = 2 },
    { label = "Electric Motor (MV)", name = "gregtech:gt.metaitem.01", damage = 32601, stock = 2 },
    { label = "Electric Motor (HV)", name = "gregtech:gt.metaitem.01", damage = 32602, stock = 2 },
    { label = "Electric Motor (EV)", name = "gregtech:gt.metaitem.01", damage = 32603, stock = 2 },
    { label = "Electric Motor (IV)", name = "gregtech:gt.metaitem.01", damage = 32604, stock = 2 },
    -- 	{label="Electric Motor (LuV)",name="gregtech:gt.metaitem.01",damage=32606,stock=64},
    -- 	{label="Electric Pump (LV)",name="gregtech:gt.metaitem.01",damage=32610,stock=64},
    { label = "Electric Pump (MV)", name = "gregtech:gt.metaitem.01", damage = 32611, stock = 2 },
    { label = "Electric Pump (HV)", name = "gregtech:gt.metaitem.01", damage = 32612, stock = 2 },
    { label = "Electric Pump (EV)", name = "gregtech:gt.metaitem.01", damage = 32613, stock = 2 },
    { label = "Electric Pump (IV)", name = "gregtech:gt.metaitem.01", damage = 32614, stock = 2 },
    -- 	{label="Electric Pump (LuV)",name="gregtech:gt.metaitem.01",damage=32615,stock=64},
    { label = "Conveyor Module (LV)", name = "gregtech:gt.metaitem.01", damage = 32630, stock = 2 },
    { label = "Conveyor Module (MV)", name = "gregtech:gt.metaitem.01", damage = 32631, stock = 2 },
    { label = "Conveyor Module (HV)", name = "gregtech:gt.metaitem.01", damage = 32632, stock = 2 },
    { label = "Conveyor Module (EV)", name = "gregtech:gt.metaitem.01", damage = 32633, stock = 2 },
    { label = "Conveyor Module (IV)", name = "gregtech:gt.metaitem.01", damage = 32634, stock = 2 },
    -- 	{label="Conveyor Module (LuV)",name="gregtech:gt.metaitem.01",damage=32635,stock=64},
    { label = "Electric Piston (LV)", name = "gregtech:gt.metaitem.01", damage = 32640, stock = 2 },
    { label = "Electric Piston (MV)", name = "gregtech:gt.metaitem.01", damage = 32641, stock = 2 },
    { label = "Electric Piston (HV)", name = "gregtech:gt.metaitem.01", damage = 32642, stock = 2 },
    -- 	{label="Electric Piston (EV)",name="gregtech:gt.metaitem.01",damage=32643,stock=64},
    { label = "Electric Piston (IV)", name = "gregtech:gt.metaitem.01", damage = 32644, stock = 2 },
    -- 	{label="Electric Piston (LuV)",name="gregtech:gt.metaitem.01",damage=32645,stock=64},
    { label = "Robot Arm (LV)", name = "gregtech:gt.metaitem.01", damage = 32650, stock = 2 },
    { label = "Robot Arm (MV)", name = "gregtech:gt.metaitem.01", damage = 32651, stock = 2 },
    { label = "Robot Arm (HV)", name = "gregtech:gt.metaitem.01", damage = 32652, stock = 2 },
    { label = "Robot Arm (IV)", name = "gregtech:gt.metaitem.01", damage = 32654, stock = 2 },
    -- 	{label="Robot Arm (LuV)",name="gregtech:gt.metaitem.01",damage=32655,stock=64},
    -- 	{label="Fluid Regulator (IV)",name="gregtech:gt.metaitem.01",damage=32664,stock=64},
    -- 	{label="Field Generator (LV)",name="gregtech:gt.metaitem.01",damage=32670,stock=64},
    { label = "Field Generator (HV)", name = "gregtech:gt.metaitem.01", damage = 32672, stock = 2 },
    -- 	{label="Field Generator (EV)",name="gregtech:gt.metaitem.01",damage=32673,stock=64},
    -- 	{label="Emitter (EV)",name="gregtech:gt.metaitem.01",damage=32683,stock=64},
    -- 	{label="Data Orb",name="gregtech:gt.metaitem.01",damage=32707,stock=64},
    -- 	{label="Epoxy Circuit Board",name="gregtech:gt.metaitem.01",damage=32711,stock=64},
    -- 	{label="Engraved Lapotron Chip",name="gregtech:gt.metaitem.01",damage=32714,stock=64},
    -- 	{label="Phenolic Circuit Board",name="gregtech:gt.metaitem.01",damage=32719,stock=64},
    { label = "Fiber-Reinforced Circuit Board", name = "gregtech:gt.metaitem.01", damage = 32720, stock = 64 },
    { label = "Quantum Eye", name = "gregtech:gt.metaitem.01", damage = 32724, stock = 16 },
     	{label="Quantum Star",name="gregtech:gt.metaitem.01",damage=32725,stock=16},
    -- 	{label="Item Filter",name="gregtech:gt.metaitem.01",damage=32729,stock=64},
    -- 	{label="Fluid Detector Cover",name="gregtech:gt.metaitem.01",damage=32732,stock=64},
    -- 	{label="Item Detector Cover",name="gregtech:gt.metaitem.01",damage=32733,stock=64},
    -- 	{label="Computer Monitor Cover",name="gregtech:gt.metaitem.01",damage=32740,stock=64},
    -- 	{label="Aluminium Casing",name="gregtech:gt.metaitem.02",damage=18019,stock=64},
    -- 	{label="Iridium Casing",name="gregtech:gt.metaitem.02",damage=18084,stock=64},
    -- 	{label="Stainless Steel Casing",name="gregtech:gt.metaitem.02",damage=18306,stock=64},
    -- 	{label="Tungstensteel Casing",name="gregtech:gt.metaitem.02",damage=18316,stock=64},
    -- 	{label="Fine Tantalum Wire",name="gregtech:gt.metaitem.02",damage=19080,stock=64},
    -- 	{label="Fine Iridium Wire",name="gregtech:gt.metaitem.02",damage=19084,stock=64},
    -- 	{label="Fine Platinum Wire",name="gregtech:gt.metaitem.02",damage=19085,stock=64},
    -- 	{label="Fine Electrum Wire",name="gregtech:gt.metaitem.02",damage=19303,stock=64},
    -- 	{label="Fine Steel Wire",name="gregtech:gt.metaitem.02",damage=19305,stock=64},
    -- 	{label="Fine Red Alloy Wire",name="gregtech:gt.metaitem.02",damage=19308,stock=64},
    -- 	{label="Fine Tungstensteel Wire",name="gregtech:gt.metaitem.02",damage=19316,stock=64},
    -- 	{label="Fine Annealed Copper Wire",name="gregtech:gt.metaitem.02",damage=19345,stock=64},
    -- 	{label="Fine Energetic Alloy Wire",name="gregtech:gt.metaitem.02",damage=19366,stock=64},
    -- 	{label="Small Stainless Steel Gear",name="gregtech:gt.metaitem.02",damage=20306,stock=64},
    -- 	{label="Small Tungstensteel Gear",name="gregtech:gt.metaitem.02",damage=20316,stock=64},
    -- 	{label="Small HSS-S Gear",name="gregtech:gt.metaitem.02",damage=20374,stock=64},
    -- 	{label="Tin Rotor",name="gregtech:gt.metaitem.02",damage=21057,stock=64},
    -- 	{label="Bronze Rotor",name="gregtech:gt.metaitem.02",damage=21300,stock=64},
    -- 	{label="Steel Rotor",name="gregtech:gt.metaitem.02",damage=21305,stock=64},
    -- 	{label="Stainless Steel Rotor",name="gregtech:gt.metaitem.02",damage=21306,stock=64},
    -- 	{label="Tungstensteel Rotor",name="gregtech:gt.metaitem.02",damage=21316,stock=64},
    -- 	{label="HSS-S Rotor",name="gregtech:gt.metaitem.02",damage=21374,stock=64},
    -- 	{label="Long Chrome Rod",name="gregtech:gt.metaitem.02",damage=22030,stock=64},
    -- 	{label="Long Iron Rod",name="gregtech:gt.metaitem.02",damage=22032,stock=64},
    -- 	{label="Long Steel Rod",name="gregtech:gt.metaitem.02",damage=22305,stock=64},
    -- 	{label="Long HSS-S Rod",name="gregtech:gt.metaitem.02",damage=22374,stock=64},
    -- 	{label="Iron Spring",name="gregtech:gt.metaitem.02",damage=24032,stock=64},
    -- 	{label="HSS-S Gear",name="gregtech:gt.metaitem.02",damage=31374,stock=64},
    -- 	{label="Plastic Circuit Board",name="gregtech:gt.metaitem.03",damage=32007,stock=64},
    { label = "SMD Resistor", name = "gregtech:gt.metaitem.03", damage = 32011, stock = 64 },
    { label = "SMD Diode", name = "gregtech:gt.metaitem.03", damage = 32016, stock = 64 },
    { label = "SMD Transistor", name = "gregtech:gt.metaitem.03", damage = 32018, stock = 64 },
    { label = "SMD Capacitor", name = "gregtech:gt.metaitem.03", damage = 32020, stock = 64 },
    -- 	{label="Monocrystalline Silicon Boule",name="gregtech:gt.metaitem.03",damage=32030,stock=64},
    -- 	{label="Phosphorus doped Monocrystalline Silicon Boule",name="gregtech:gt.metaitem.03",damage=32031,stock=64},
    -- 	{label="Naquadah doped Monocrystalline Silicon Boule",name="gregtech:gt.metaitem.03",damage=32032,stock=64},
    -- 	{label="Wafer",name="gregtech:gt.metaitem.03",damage=32033,stock=64},
    -- 	{label="Phosphorus doped Wafer",name="gregtech:gt.metaitem.03",damage=32034,stock=64},
    -- 	{label="Naquadah doped Wafer",name="gregtech:gt.metaitem.03",damage=32035,stock=64},
    -- 	{label="Random Access Memory Chip (Wafer)",name="gregtech:gt.metaitem.03",damage=32038,stock=64},
    { label = "Random Access Memory Chip", name = "gregtech:gt.metaitem.03", damage = 32039, stock = 64 },
    -- 	{label="NAND Memory Chip (Wafer)",name="gregtech:gt.metaitem.03",damage=32040,stock=64},
    { label = "NAND Memory Chip", name = "gregtech:gt.metaitem.03", damage = 32041, stock = 64 },
    -- 	{label="NOR Memory Chip (Wafer)",name="gregtech:gt.metaitem.03",damage=32042,stock=64},
    { label = "NOR Memory Chip", name = "gregtech:gt.metaitem.03", damage = 32043, stock = 64 },
    -- 	{label="Central Processing Unit (Wafer)",name="gregtech:gt.metaitem.03",damage=32044,stock=64},
    { label = "Central Processing Unit", name = "gregtech:gt.metaitem.03", damage = 32045, stock = 64 },
    -- 	{label="PIC Wafer",name="gregtech:gt.metaitem.03",damage=32050,stock=64},
    -- 	{label="Power IC",name="gregtech:gt.metaitem.03",damage=32051,stock=64},
    { label = "HPIC Wafer", name = "gregtech:gt.metaitem.03", damage = 32052, stock = 8 },
    { label = "High Power IC", name = "gregtech:gt.metaitem.03", damage = 32053, stock = 8 },
    { label = "NanoCPU Wafer", name = "gregtech:gt.metaitem.03", damage = 32054, stock = 8 },
    -- 	{label="Nanocomponent Central Processing Unit",name="gregtech:gt.metaitem.03",damage=32055,stock=64},
    { label = "QBit Wafer", name = "gregtech:gt.metaitem.03", damage = 32056, stock = 8 },
    -- 	{label="QBit Processing Unit",name="gregtech:gt.metaitem.03",damage=32057,stock=64},
    -- 	{label="UHPIC Wafer",name="gregtech:gt.metaitem.03",damage=32058,stock=64},
    -- 	{label="Ultra High Power IC",name="gregtech:gt.metaitem.03",damage=32059,stock=64},
    { label = "NAND Chip", name = "gregtech:gt.metaitem.03", damage = 32075, stock = 16 },
    { label = "Microprocessor", name = "gregtech:gt.metaitem.03", damage = 32078, stock = 32 },
    { label = "Integrated Processor", name = "gregtech:gt.metaitem.03", damage = 32080, stock = 32 },
    { label = "Nano Processor", name = "gregtech:gt.metaitem.03", damage = 32082, stock = 32 },
    { label = "Quantum Processor", name = "gregtech:gt.metaitem.03", damage = 32085, stock = 32 },
    { label = "Quantum Assembly", name = "gregtech:gt.metaitem.03", damage = 32086, stock = 32 },
    { label = "Quantum Supercomputer", name = "gregtech:gt.metaitem.03", damage = 32087, stock = 16 },
    { label = "Quantum Mainframe", name = "gregtech:gt.metaitem.03", damage = 32088, stock = 8 },
    { label = "Circuit Board", name = "gregtech:gt.metaitem.03", damage = 32100, stock = 64 },
    -- 	{label="Good Circuit Board",name="gregtech:gt.metaitem.03",damage=32101,stock=64},
    { label = "Advanced Circuit Board", name = "gregtech:gt.metaitem.03", damage = 32102, stock = 512 },
    { label = "More Advanced Circuit Board", name = "gregtech:gt.metaitem.03", damage = 32103, stock = 512 },
    { label = "Plastic Circuit Board", name = "gregtech:gt.metaitem.03", damage = 32106, stock = 512 },
    -- 	{label="High Voltage Coil",name="gregtech:gt.metaitem.03",damage=32143,stock=64},
    -- 	{label="Extreme Voltage Coil",name="gregtech:gt.metaitem.03",damage=32144,stock=64},
    -- 	{label="Insane Voltage Coil",name="gregtech:gt.metaitem.03",damage=32145,stock=64},
    -- 	{label="Ludicrous Voltage Coil",name="gregtech:gt.metaitem.03",damage=32146,stock=64},
    { label = "SMD Inductor", name = "gregtech:gt.metaitem.03", damage = 32182, stock = 64 },
    -- 	{label="Gallium Arsenide Crystal",name="gregtech:gt.metaitem.03",damage=32190,stock=64},
    -- 	{label="Small Gallium Arsenide Crystal",name="gregtech:gt.metaitem.03",damage=32191,stock=64},
    -- 	{label="60k He Coolant Cell",name="gregtech:gt.60k_Helium_Coolantcell",damage=0,stock=1},
    -- 	{label="180k He Coolant Cell",name="gregtech:gt.180k_Helium_Coolantcell",damage=0,stock=1},
    -- 	{label="Fuel Rod (Uranium)",name="gregtech:gt.rodUranium",damage=0,stock=64},
    { label = "Quad Fuel Rod (Uranium)", name = "gregtech:gt.rodUranium4", damage = 0, stock = 8 },
    -- 	{label="Fuel Rod (Mox)",name="gregtech:gt.rodMOX",damage=0,stock=64},
    { label = "Quad Fuel Rod (Mox)", name = "gregtech:gt.rodMOX4", damage = 0, stock = 8 },
    -- 	{label="Graphics Card (Tier 3)",name="OpenComputers:item",damage=10,stock=64},
    -- 	{label="Network Card",name="OpenComputers:item",damage=11,stock=64},
    -- 	{label="Wireless Network Card (Tier 2)",name="OpenComputers:item",damage=13,stock=64},
    -- 	{label="Microchip (Tier 1)",name="OpenComputers:item",damage=24,stock=64},
    -- 	{label="Microchip (Tier 2)",name="OpenComputers:item",damage=25,stock=64},
    -- 	{label="Microchip (Tier 3)",name="OpenComputers:item",damage=26,stock=64},
    -- 	{label="Arithmetic Logic Unit (ALU)",name="OpenComputers:item",damage=27,stock=64},
    -- 	{label="Control Unit (CU)",name="OpenComputers:item",damage=28,stock=64},
    -- 	{label="Memory (Tier 3)",name="OpenComputers:item",damage=38,stock=64},
    -- 	{label="Central Processing Unit (CPU) (Tier 3)",name="OpenComputers:item",damage=43,stock=64},
    -- 	{label="Inventory Upgrade",name="OpenComputers:item",damage=53,stock=64},
    -- 	{label="Inventory Controller Upgrade",name="OpenComputers:item",damage=61,stock=64},
    -- 	{label="Tank Upgrade",name="OpenComputers:item",damage=76,stock=64},
    -- 	{label="Tank Controller Upgrade",name="OpenComputers:item",damage=77,stock=64},
    -- 	{label="XP Bucket",name="OpenBlocks:filledbucket",damage=0,stock=1},
    -- 	{label="Gregtech Computer Cube",name="miscutils:MU-metaitem.01",damage=32055,stock=64},
    -- 	{label="White Metal Dust",name="miscutils:itemDustWhiteMetal",damage=0,stock=64},
    -- 	{label="Sodium Nitrate Dust",name="miscutils:itemDustSodiumNitrate",damage=0,stock=64},
    -- 	{label="Zirconium Carbide Dust",name="miscutils:itemDustZirconiumCarbide",damage=0,stock=64},
    -- 	{label="Tumbaga Ingot",name="miscutils:itemIngotTumbaga",damage=0,stock=64},
    -- 	{label="Tumbaga Dust",name="miscutils:itemDustTumbaga",damage=0,stock=64},
    -- 	{label="Tumbaga Rod",name="miscutils:itemRodTumbaga",damage=0,stock=64},
    -- 	{label="Potin Plate",name="miscutils:itemPlatePotin",damage=0,stock=64},
    -- 	{label="Potin Rod",name="miscutils:itemRodPotin",damage=0,stock=64},
    -- 	{label="Long Potin Rod",name="miscutils:itemRodLongPotin",damage=0,stock=64},
    -- 	{label="Staballoy Dust",name="miscutils:itemDustStaballoy",damage=0,stock=64},
    -- 	{label="Inconel-625 Ingot",name="miscutils:itemIngotInconel625",damage=0,stock=64},
    -- 	{label="Inconel-625 Plate",name="miscutils:itemPlateInconel625",damage=0,stock=64},
    -- 	{label="Inconel-625 Rod",name="miscutils:itemRodInconel625",damage=0,stock=64},
    -- 	{label="Inconel-690 Dust",name="miscutils:itemDustInconel690",damage=0,stock=64},
    -- 	{label="Inconel-792 Ingot",name="miscutils:itemIngotInconel792",damage=0,stock=64},
    -- 	{label="Inconel-792 Dust",name="miscutils:itemDustInconel792",damage=0,stock=64},
    -- 	{label="Inconel-792 Plate",name="miscutils:itemPlateInconel792",damage=0,stock=64},
    -- 	{label="Eglin Steel Ingot",name="miscutils:itemIngotEglinSteel",damage=0,stock=64},
    -- 	{label="Eglin Steel Dust",name="miscutils:itemDustEglinSteel",damage=0,stock=64},
    -- 	{label="Eglin Steel Plate",name="miscutils:itemPlateEglinSteel",damage=0,stock=64},
    -- 	{label="Eglin Steel Rod",name="miscutils:itemRodEglinSteel",damage=0,stock=64},
    -- 	{label="Maraging Steel 250 Plate",name="miscutils:itemPlateMaragingSteel250",damage=0,stock=64},
    -- 	{label="Maraging Steel 300 Plate",name="miscutils:itemPlateMaragingSteel300",damage=0,stock=64},
    -- 	{label="Maraging Steel 300 Gear",name="miscutils:itemGearMaragingSteel300",damage=0,stock=64},
    -- 	{label="Watertight Steel Ingot",name="miscutils:itemIngotWatertightSteel",damage=0,stock=64},
    -- 	{label="Watertight Steel Rod",name="miscutils:itemRodWatertightSteel",damage=0,stock=64},
    -- 	{label="Stellite Ingot",name="miscutils:itemIngotStellite",damage=0,stock=64},
    -- 	{label="Stellite Dust",name="miscutils:itemDustStellite",damage=0,stock=64},
    -- 	{label="Talonite Ingot",name="miscutils:itemIngotTalonite",damage=0,stock=64},
    -- 	{label="Talonite Dust",name="miscutils:itemDustTalonite",damage=0,stock=64},
    -- 	{label="Talonite Plate",name="miscutils:itemPlateTalonite",damage=0,stock=64},
    -- 	{label="Talonite Rod",name="miscutils:itemRodTalonite",damage=0,stock=64},
    -- 	{label="Hastelloy-W Ingot",name="miscutils:itemIngotHastelloyW",damage=0,stock=64},
    -- 	{label="Hastelloy-W Gear",name="miscutils:itemGearHastelloyW",damage=0,stock=64},
    -- 	{label="Hastelloy-X Ingot",name="miscutils:itemIngotHastelloyX",damage=0,stock=64},
    -- 	{label="Hastelloy-X Rod",name="miscutils:itemRodHastelloyX",damage=0,stock=64},
    -- 	{label="Hastelloy-N Ingot",name="miscutils:itemIngotHastelloyN",damage=0,stock=64},
    -- 	{label="Double Hastelloy-N Plate",name="miscutils:itemPlateDoubleHastelloyN",damage=0,stock=64},
    -- 	{label="Grisium Dust",name="miscutils:itemDustGrisium",damage=0,stock=64},
    -- 	{label="Catalyst Carrier",name="miscutils:item.BasicAgrichemItem",damage=13,stock=64},
    -- 	{label="Blue Metal Catalyst",name="miscutils:item.BasicGenericChemItem",damage=2,stock=64},
    -- 	{label="Blazing Pyrotheum Bucket",name="miscutils:bucket",damage=1,stock=1},
    -- 	{label="Growth Medium",name="Genetics:misc",damage=4,stock=64},
    -- 	{label="Integrated Circuit Board",name="Genetics:misc",damage=9,stock=64},
    -- 	{label="Amorphic Catalyst",name="BloodArsenal:amorphic_catalyst",damage=0,stock=64},
    -- 	{label="Draconium Ingot",name="DraconicEvolution:draconiumIngot",damage=0,stock=64},
    -- 	{label="Small Fuel Canister",name="GalaxySpace:item.ModuleSmallFuelCanister",damage=0,stock=64},
    -- 	{label="Blank Fuel Tank",name="GalaxySpace:item.ModuleSmallCanister",damage=0,stock=64},
    -- 	{label="Compressed Coal",name="GalaxySpace:item.CompressedCoal",damage=0,stock=64},
    -- 	{label="Compressed Dual Bronze",name="GalaxySpace:item.CompressedDualBronze",damage=0,stock=64},
    -- 	{label="Compressed Dual Aluminium",name="GalaxySpace:item.CompressedDualAluminium",damage=0,stock=64},
    -- 	{label="Compressed Alloy \"SDHC-120\"",name="GalaxySpace:item.CompressedSDHD120",damage=0,stock=64},
    -- 	{label="Compressed Duralumin",name="GalaxySpace:item.CompressedPlates",damage=2,stock=64},
    -- 	{label="Compressed Lead",name="GalaxySpace:item.CompressedPlates",damage=3,stock=64},
    -- 	{label="Compressed Mithril",name="GalaxySpace:item.CompressedPlates",damage=5,stock=64},
    -- 	{label="Compressed Nickel",name="GalaxySpace:item.CompressedPlates",damage=6,stock=64},
    -- 	{label="Rocket Control Computer Tier 4",name="GalaxySpace:item.RocketControlComputer",damage=4,stock=64},
    -- 	{label="§61k§r ME Essentia Storage Component",name="thaumicenergistics:storage.component",damage=0,stock=64},
    -- 	{label="§e4k§r ME Essentia Storage Component",name="thaumicenergistics:storage.component",damage=1,stock=64},
    -- 	{label="§a16k§r ME Essentia Storage Component",name="thaumicenergistics:storage.component",damage=2,stock=64},
    -- 	{label="§b64k§r ME Essentia Storage Component",name="thaumicenergistics:storage.component",damage=3,stock=64},
    -- 	{label="§9256k§r ME Essentia Storage Component",name="thaumicenergistics:storage.component",damage=5,stock=64},
    -- 	{label="Circuit Plate",name="ProjRed|Core:projectred.core.part",damage=0,stock=64},
    -- 	{label="Conductive Plate",name="ProjRed|Core:projectred.core.part",damage=1,stock=64},
    -- 	{label="Anode",name="ProjRed|Core:projectred.core.part",damage=4,stock=64},
    -- 	{label="Cathode",name="ProjRed|Core:projectred.core.part",damage=5,stock=64},
    -- 	{label="Red Alloy Wire",name="ProjRed|Transmission:projectred.transmission.wire",damage=0,stock=64},
    -- 	{label="Thorianite Dust",name="bartworks:gt.bwMetaGenerateddust",damage=18,stock=64},
    -- 	{label="Platinum Salt Dust",name="bartworks:gt.bwMetaGenerateddust",damage=45,stock=64},
    -- 	{label="Platinum Residue Dust",name="bartworks:gt.bwMetaGenerateddust",damage=49,stock=64},
    -- 	{label="Reprecipitated Platinum Dust",name="bartworks:gt.bwMetaGenerateddust",damage=51,stock=64},
    -- 	{label="Potassium Disulfate Dust",name="bartworks:gt.bwMetaGenerateddust",damage=59,stock=64},
    -- 	{label="Calcium Chloride Dust",name="bartworks:gt.bwMetaGenerateddust",damage=63,stock=64},
    -- 	{label="Ruthenium Dust",name="bartworks:gt.bwMetaGenerateddust",damage=64,stock=64},
    -- 	{label="Ruthenium Tetroxide Dust",name="bartworks:gt.bwMetaGenerateddust",damage=66,stock=64},
    -- 	{label="Iridium Chloride Dust",name="bartworks:gt.bwMetaGenerateddust",damage=76,stock=64},
    -- 	{label="Rhodium Dust",name="bartworks:gt.bwMetaGenerateddust",damage=78,stock=64},
    -- 	{label="Crude Rhodium Metal Dust",name="bartworks:gt.bwMetaGenerateddust",damage=79,stock=64},
    -- 	{label="Rhodium Nitrate Dust",name="bartworks:gt.bwMetaGenerateddust",damage=83,stock=64},
    -- 	{label="Rhodium Filter Cake Dust",name="bartworks:gt.bwMetaGenerateddust",damage=85,stock=64},
    -- 	{label="Reprecipitated Rhodium Dust",name="bartworks:gt.bwMetaGenerateddust",damage=87,stock=64},
    -- 	{label="Rhodium-Plated Palladium Dust",name="bartworks:gt.bwMetaGenerateddust",damage=88,stock=64},
    -- 	{label="Ruridit Dust",name="bartworks:gt.bwMetaGenerateddust",damage=90,stock=64},
    -- 	{label="Incoloy-903 Dust",name="bartworks:gt.bwMetaGenerateddust",damage=10084,stock=64},
    -- 	{label="Dephosphated Samarium Concentrate Dust",name="bartworks:gt.bwMetaGenerateddust",damage=11129,stock=64},
    -- 	{label="Tungstic Acid Dust",name="bartworks:gt.bwMetaGenerateddust",damage=29900,stock=64},
    -- 	{label="Tungsten Trioxide Dust",name="bartworks:gt.bwMetaGenerateddust",damage=29901,stock=64},
    -- 	{label="Tiny Pile of Ruridit Dust",name="bartworks:gt.bwMetaGenerateddustTiny",damage=90,stock=64},
    -- 	{label="Rhodium Ingot",name="bartworks:gt.bwMetaGeneratedingot",damage=78,stock=64},
    { label = "Rhodium-Plated Palladium Ingot", name = "bartworks:gt.bwMetaGeneratedingot", damage = 88, stock = 64 },
     	{label="Ruridit Ingot",name="bartworks:gt.bwMetaGeneratedingot",damage=90,stock=64},
    -- 	{label="Incoloy-903 Ingot",name="bartworks:gt.bwMetaGeneratedingot",damage=10084,stock=64},
    -- 	{label="Rhodium-Plated Palladium Plate",name="bartworks:gt.bwMetaGeneratedplate",damage=88,stock=64},
    -- 	{label="Rhodium-Plated Palladium Gear",name="bartworks:gt.bwMetaGeneratedgearGt",damage=88,stock=64},
    -- 	{label="Ruridit Bolt",name="bartworks:gt.bwMetaGeneratedbolt",damage=90,stock=64},
    -- 	{label="Rhodium-Plated Palladium Screw",name="bartworks:gt.bwMetaGeneratedscrew",damage=88,stock=64},
    -- 	{label="Fine Ruridit Wire",name="bartworks:gt.bwMetaGeneratedwireFine",damage=90,stock=64},
     	{label="Double Rhodium-Plated Palladium Plate",name="bartworks:gt.bwMetaGeneratedplateDouble",damage=88,stock=64},
    -- 	{label="Ichor",name="ThaumicTinkerer:kamiResource",damage=0,stock=64},
    -- 	{label="Stone Slab",name="etfuturum:stone_slab",damage=0,stock=64},
}
return STOCKING
