local STOCKING = {
    -- 	{label="Block of Diamond",damage=0,name="minecraft:diamond_block",stock=64},
    -- 	{label="Reinforced Glass",damage=0,name="IC2:blockAlloyGlass",stock=64},
    -- 	{label="Quartz Glass",damage=0,name="appliedenergistics2:tile.BlockQuartzGlass",stock=64},
    -- 	{label="Water Bucket",damage=0,name="minecraft:water_bucket",stock=1},
    -- 	{label="Lava Bucket",damage=0,name="minecraft:lava_bucket",stock=1},
    -- 	{label="Clay",damage=0,name="minecraft:clay_ball",stock=64},
    -- 	{label="Eye of Ender",damage=0,name="minecraft:ender_eye",stock=64},
    -- 	{label="Nether Star",damage=0,name="minecraft:nether_star",stock=64},
    -- 	{label="ME Drive",damage=0,name="appliedenergistics2:tile.BlockDrive",stock=64},
    -- 	{label="ME Chest",damage=0,name="appliedenergistics2:tile.BlockChest",stock=64},
    -- 	{label="ME Interface",damage=0,name="appliedenergistics2:tile.BlockInterface",stock=64},
    -- 	{label="Crafting Unit",damage=0,name="appliedenergistics2:tile.BlockCraftingUnit",stock=64},
    -- 	{label="Crafting Co-Processing Unit",damage=1,name="appliedenergistics2:tile.BlockCraftingUnit",stock=64},
    -- 	{label="Arcane Stone Block",damage=6,name="Thaumcraft:blockCosmeticSolid",stock=64},
    -- 	{label="Water Crystal Cluster",damage=2,name="Thaumcraft:blockCrystal",stock=64},
    -- 	{label="Mixed Crystal Cluster",damage=6,name="Thaumcraft:blockCrystal",stock=64},
    -- 	{label="Arcane Pedestal",damage=1,name="Thaumcraft:blockStoneDevice",stock=64},
    -- 	{label="Thickened Glass",damage=0,name="ExtraUtilities:decorativeBlock2",stock=64},
    -- 	{label="Obsidian Glass",damage=5,name="ExtraUtilities:decorativeBlock2",stock=64},
    -- 	{label="Clear Glass",damage=0,name="TConstruct:GlassBlock",stock=64},
    -- 	{label="Ritual Stone",damage=0,name="AWWayofTime:ritualStone",stock=64},
    -- 	{label="Imperfect Ritual Stone",damage=0,name="AWWayofTime:imperfectRitualStone",stock=64},
    -- 	{label="Tank",damage=0,name="BuildCraft|Factory:tankBlock",stock=64},
    -- 	{label="Iron Chest",damage=0,name="IronChest:BlockIronChest",stock=64},
    -- 	{label="Steel Chest",damage=4,name="IronChest:BlockIronChest",stock=64},
    -- 	{label="Obsidian Chest",damage=6,name="IronChest:BlockIronChest",stock=64},
    -- 	{label="Endoflame",damage=0,name="Botania:specialFlower",stock=64},
    -- 	{label="ULV Machine Hull",damage=10,name="gregtech:gt.blockmachines",stock=64},
    { label = "LV Machine Hull", damage = 11, name = "gregtech:gt.blockmachines", stock = 8 },
    { label = "MV Machine Hull", damage = 12, name = "gregtech:gt.blockmachines", stock = 8 },
    { label = "HV Machine Hull", damage = 13, name = "gregtech:gt.blockmachines", stock = 8 },
    { label = "EV Machine Hull", damage = 14, name = "gregtech:gt.blockmachines", stock = 8 },
    { label = "IV Machine Hull", damage = 15, name = "gregtech:gt.blockmachines", stock = 1 },
    -- 	{label="EV Dynamo Hatch",damage=34,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="IV Dynamo Hatch",damage=35,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="HV Energy Hatch",damage=43,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="EV Energy Hatch",damage=44,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="IV Energy Hatch",damage=45,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Input Hatch (ULV)",damage=50,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Output Hatch (ULV)",damage=60,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Output Hatch (HV)",damage=63,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Input Bus (ULV)",damage=70,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Input Bus (LV)",damage=71,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Output Bus (ULV)",damage=80,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Output Bus (LV)",damage=81,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Output Bus (HV)",damage=83,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Lead Cable",damage=1226,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Tin Wire",damage=1240,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Tin Cable",damage=1246,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="2x Cupronickel Wire",damage=1341,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Cupronickel Cable",damage=1346,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Copper Wire",damage=1360,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Copper Cable",damage=1366,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="4x Copper Cable",damage=1368,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Annealed Copper Wire",damage=1380,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Annealed Copper Cable",damage=1386,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Gold Wire",damage=1420,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Gold Cable",damage=1426,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="4x Electrum Wire",damage=1442,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="2x Silver Wire",damage=1461,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="2x Silver Cable",damage=1467,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="4x Black Steel Wire",damage=1542,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Aluminium Wire",damage=1580,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="2x Aluminium Wire",damage=1581,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Aluminium Cable",damage=1586,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="2x Aluminium Cable",damage=1587,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="4x Graphene Wire",damage=1602,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Platinum Wire",damage=1640,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Platinum Cable",damage=1646,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Tungsten Wire",damage=1680,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="2x Tungsten Wire",damage=1681,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Tungsten Cable",damage=1686,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="2x Tungsten Cable",damage=1687,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="1x Superconductor IV Wire",damage=2380,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Steel Fluid Pipe",damage=5132,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="Tungstensteel Fluid Pipe",damage=5162,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="PTFE Fluid Pipe",damage=5682,name="gregtech:gt.blockmachines",stock=64},
    -- 	{label="ULV Machine Casing",damage=0,name="gregtech:gt.blockcasings",stock=64},
    { label = "LV Machine Casing", damage = 1, name = "gregtech:gt.blockcasings", stock = 8 },
    { label = "MV Machine Casing", damage = 2, name = "gregtech:gt.blockcasings", stock = 8 },
    { label = "HV Machine Casing", damage = 3, name = "gregtech:gt.blockcasings", stock = 8 },
    { label = "EV Machine Casing", damage = 4, name = "gregtech:gt.blockcasings", stock = 8 },
    { label = "IV Machine Casing", damage = 5, name = "gregtech:gt.blockcasings", stock = 1 },
    -- 	{label="Bronze Plated Bricks",damage=10,name="gregtech:gt.blockcasings",stock=64},
    -- 	{label="Solid Steel Machine Casing",damage=0,name="gregtech:gt.blockcasings2",stock=64},
    -- 	{label="Steel Gear Box Casing",damage=3,name="gregtech:gt.blockcasings2",stock=64},
    -- 	{label="Assembly Line Casing",damage=5,name="gregtech:gt.blockcasings2",stock=64},
    -- 	{label="Clean Stainless Steel Machine Casing",damage=1,name="gregtech:gt.blockcasings4",stock=64},
    -- 	{label="Cupronickel Coil Block",damage=0,name="gregtech:gt.blockcasings5",stock=64},
    -- 	{label="HSS-G Coil Block",damage=4,name="gregtech:gt.blockcasings5",stock=64},
    -- 	{label="Hermetic Casing I",damage=1,name="gregtech:gt.blockcasings6",stock=64},
    -- 	{label="Block of Endereye",damage=7,name="gregtech:gt.blockgem1",stock=64},
    -- 	{label="Transposer",damage=0,name="OpenComputers:transposer",stock=64},
    -- 	{label="Tumbaga Frame Box",damage=0,name="miscutils:blockFrameGtTumbaga",stock=64},
    -- 	{label="Iron Tank",damage=0,name="irontank:ironTank",stock=64},
    -- 	{label="Pyrolyse Oven Casing",damage=2,name="gregtech:gt.blockcasingsNH",stock=64},
    -- 	{label="Material Press Machine Casing",damage=4,name="miscutils:miscutils.blockcasings",stock=64},
    -- 	{label="Aluminium Frame Box",damage=19,name="gregtech:gt.blockframes",stock=64},
    -- 	{label="Titanium Frame Box",damage=28,name="gregtech:gt.blockframes",stock=64},
    -- 	{label="Steel Frame Box",damage=305,name="gregtech:gt.blockframes",stock=64},
    -- 	{label="Tungstensteel Frame Box",damage=316,name="gregtech:gt.blockframes",stock=64},
    -- 	{label="Energium Dust",damage=2,name="IC2:itemDust2",stock=64},
    -- 	{label="Enriched Uranium Nuclear Fuel",damage=0,name="IC2:itemUran",stock=64},
    -- 	{label="MOX Nuclear Fuel",damage=0,name="IC2:itemMOX",stock=64},
    -- 	{label="Plutonium",damage=0,name="IC2:itemPlutonium",stock=64},
    -- 	{label="Tiny Pile of Uranium 235",damage=0,name="IC2:itemUran235small",stock=64},
    -- 	{label="Uranium 238",damage=0,name="IC2:itemUran238",stock=64},
     	{label="Raw Carbon Fibre",damage=0,name="IC2:itemPartCarbonFibre",stock=256},
    -- 	{label="Lapotron Crystal",damage=26,name="IC2:itemBatLamaCrystal",stock=1},
    -- 	{label="Industrial Diamond",damage=0,name="IC2:itemPartIndustrialDiamond",stock=64},
    -- 	{label="Fluix Crystal",damage=7,name="appliedenergistics2:item.ItemMultiMaterial",stock=64},
    -- 	{label="Fluix Dust",damage=8,name="appliedenergistics2:item.ItemMultiMaterial",stock=64},
    { label = "Printed Calculation Circuit", damage = 16, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 64 },
    { label = "Printed Engineering Circuit", damage = 17, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 64 },
    { label = "Printed Logic Circuit", damage = 18, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 64 },
    { label = "Printed Silicon", damage = 20, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 64 },
    { label = "Logic Processor", damage = 22, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 64 },
    { label = "Calculation Processor", damage = 23, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 64 },
    { label = "Engineering Processor", damage = 24, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 64 },
    -- 	{label="§e4k§r ME Storage Component",damage=36,name="appliedenergistics2:item.ItemMultiMaterial",stock=64},
    -- 	{label="§a16k§r ME Storage Component",damage=37,name="appliedenergistics2:item.ItemMultiMaterial",stock=64},
    -- 	{label="§b64k§r ME Storage Component",damage=38,name="appliedenergistics2:item.ItemMultiMaterial",stock=64},
    -- 	{label="Formation Core",damage=43,name="appliedenergistics2:item.ItemMultiMaterial",stock=64},
    -- 	{label="Annihilation Core",damage=44,name="appliedenergistics2:item.ItemMultiMaterial",stock=64},
    { label = "Blank Pattern", damage = 52, name = "appliedenergistics2:item.ItemMultiMaterial", stock = 32 },
    { label = "ME Glass Cable - Fluix", damage = 16, name = "appliedenergistics2:item.ItemMultiPart", stock = 64 },
    -- 	{label="ME Storage Bus",damage=220,name="appliedenergistics2:item.ItemMultiPart",stock=64},
    -- 	{label="ME Level Emitter",damage=280,name="appliedenergistics2:item.ItemMultiPart",stock=64},
    { label = "ME Interface", damage = 440, name = "appliedenergistics2:item.ItemMultiPart", stock = 8 },
    { label = "P2P Tunnel - ME", damage = 460, name = "appliedenergistics2:item.ItemMultiPart", stock = 8 },
    -- 	{label="Wet Concrete",stock=2304,damage=0,name="wet.concrete",is_fluid=true},
    -- 	{label="2-Ethylanthrahydroquinone",stock=1000,damage=0,name="fluid.2ethylanthrahydroquinone",is_fluid=true},
    -- 	{label="Molten Gallium Arsenide",stock=288,damage=0,name="molten.galliumarsenide",is_fluid=true},
    -- 	{label="Sodium Formate",stock=1000,damage=0,name="sodium formate",is_fluid=true},
    -- 	{label="Hydrofluoric Acid",stock=1000,damage=0,name="hydrofluoricacid_gt5u",is_fluid=true},
    -- 	{label="Hydrochloric Acid",stock=1000,damage=0,name="hydrochloricacid_gt5u",is_fluid=true},
    -- 	{label="Rhodium Sulfate",stock=360,damage=0,name="rhodium sulfate",is_fluid=true},
    -- 	{label="Molten Potassium Disulfate",stock=144,damage=0,name="molten.potassium disulfate",is_fluid=true},
    -- 	{label="Silicon Tetrachloride",stock=1000,damage=0,name="silicontetrachloride",is_fluid=true},
    -- 	{label="Acidic Iridium Solution",stock=1000,damage=0,name="acidic iridium solution",is_fluid=true},
    -- 	{label="3,3-Dichlorobenzidine",stock=1000,damage=0,name="3,3dichlorobenzidine",is_fluid=true},
    -- 	{label="Helium",stock=9000,damage=0,name="helium",is_fluid=true},
    -- 	{label="Palladium Enriched Ammonia",stock=3600,damage=0,name="palladium enriched ammonia",is_fluid=true},
    -- 	{label="Rhodium Sulfate Solution",stock=39600,damage=0,name="rhodium sulfate solution",is_fluid=true},
    -- 	{label="Lead-Zinc Solution",stock=8000,damage=0,name="leadzincsolution",is_fluid=true},
    -- 	{label="Rhodium Salt Solution",stock=200,damage=0,name="rhodium salt solution",is_fluid=true},
    -- 	{label="Ammonia",stock=1000,damage=0,name="ammonia",is_fluid=true},
    -- 	{label="Hot Ruthenium Tetroxide Solution",stock=2000,damage=0,name="hot ruthenium tetroxide solution",is_fluid=true},
    -- 	{label="Formic Acid",stock=2000,damage=0,name="formic acid",is_fluid=true},
    -- 	{label="Liquid Helium",stock=1000,damage=0,name="liquid helium",is_fluid=true},
    -- 	{label="Deuterium",stock=1000,damage=0,name="deuterium",is_fluid=true},
    -- 	{label="Dichlorobenzene",stock=1000,damage=0,name="dichlorobenzene",is_fluid=true},
    -- 	{label="1,2-Dimethylbenzene",stock=1000,damage=0,name="dimethylbenzene",is_fluid=true},
    -- 	{label="Hydrogen",stock=1000,damage=0,name="hydrogen",is_fluid=true},
    -- 	{label="Sodium Tungstate",stock=1000,damage=0,name="sodium tungstate",is_fluid=true},
    -- 	{label="Molten Polybenzimidazole",stock=1000,damage=0,name="molten.polybenzimidazole",is_fluid=true},
    -- 	{label="Phthalic Acid",stock=1000,damage=0,name="phtalicacid",is_fluid=true},
    -- 	{label="Molten Polyphenylene Sulfide",stock=1500,damage=0,name="molten.polyphenylenesulfide",is_fluid=true},
    -- 	{label="2-Nitrochlorobenzene",stock=1000,damage=0,name="2nitrochlorobenzene",is_fluid=true},
    -- 	{label="Ruthenium Tetroxide Solution",stock=9000,damage=0,name="ruthenium tetroxide solution",is_fluid=true},
    -- 	{label="Platinum Concentrate",stock=18000,damage=0,name="platinum concentrate",is_fluid=true},
    -- 	{label="Indium Concentrate",stock=8000,damage=0,name="indiumconcentrate",is_fluid=true},
    -- 	{label="Hydrazine",stock=1000,damage=0,name="fluid.hydrazine",is_fluid=true},
    -- 	{label="Osmium Solution",stock=100,damage=0,name="osmium solution",is_fluid=true},
    -- 	{label="Molten Naquadah",stock=144,damage=0,name="molten.naquadah",is_fluid=true},
    -- 	{label="Chlorobenzene",stock=1000,damage=0,name="chlorobenzene",is_fluid=true},
    -- 	{label="Rhodium Filter Cake Solution",stock=1000,damage=0,name="rhodium filter cake solution",is_fluid=true},
    -- 	{label="Nitric Acid",stock=1000,damage=0,name="nitricacid",is_fluid=true},
    -- 	{label="2-Ethylanthraquinone",stock=5000,damage=0,name="fluid.2ethylanthraquinone",is_fluid=true},
    -- 	{label="Diphenyl Isophthalate",stock=1000,damage=0,name="diphenylisophtalate",is_fluid=true},
    -- 	{label="Tetrafluoroethylene",stock=1000,damage=0,name="tetrafluoroethylene",is_fluid=true},
    -- 	{label="Dense Hydrazine Fuel Mixture",stock=10000,damage=0,name="fluid.rocketfuelmixd",is_fluid=true},
    -- 	{label="Acidic Osmium Solution",stock=1000,damage=0,name="acidic osmium solution",is_fluid=true},
    -- 	{label="3,3-Diaminobenzidine",stock=1000,damage=0,name="3,3diaminobenzidine",is_fluid=true},
    -- 	{label="Ruthenium Tetroxide",stock=36000,damage=0,name="ruthenium tetroxide",is_fluid=true},
    -- 	{label="Molten Polytetrafluoroethylene",stock=216,damage=0,name="molten.polytetrafluoroethylene",is_fluid=true},
    -- 	{label="Hydrogen Peroxide",stock=5000,damage=0,name="fluid.hydrogenperoxide",is_fluid=true},
    -- 	{label="Chlorine",stock=1000,damage=0,name="chlorine",is_fluid=true},
    -- 	{label="Sodium Persulfate",stock=1000,damage=0,name="sodiumpersulfate",is_fluid=true},
    -- 	{label="Ammonium Chloride",stock=1000,damage=0,name="ammonium chloride",is_fluid=true},
     	{label="ME Dual Interface",damage=0,name="ae2fc:part_fluid_interface",stock=4},
     	{label="ME Fluid Storage Bus",damage=0,name="ae2fc:part_fluid_storage_bus",stock=1},
    -- 	{label="Glass Phial",damage=0,name="Thaumcraft:ItemEssence",stock=64},
    -- 	{label="Heavy Duty Plate",damage=0,name="GalacticraftCore:item.heavyPlating",stock=64},
    -- 	{label="Empty Canister",damage=1001,name="GalacticraftCore:item.oilCanisterPartial",stock=1},
    -- 	{label="Compressed Aluminum",damage=8,name="GalacticraftCore:item.basicItem",stock=64},
    -- 	{label="Compressed Steel",damage=9,name="GalacticraftCore:item.basicItem",stock=64},
    -- 	{label="Compressed Bronze",damage=10,name="GalacticraftCore:item.basicItem",stock=64},
    -- 	{label="Compressed Meteoric Iron",damage=1,name="GalacticraftCore:item.meteoricIronIngot",stock=64},
    -- 	{label="Heavy Duty Plate",damage=0,name="GalacticraftMars:item.itemBasicAsteroids",stock=64},
    -- 	{label="Compressed Titanium",damage=6,name="GalacticraftMars:item.itemBasicAsteroids",stock=64},
    -- 	{label="Heavy Duty Plate",damage=3,name="GalacticraftMars:item.null",stock=64},
    -- 	{label="Compressed Desh",damage=5,name="GalacticraftMars:item.null",stock=64},
    -- 	{label="Incendium",damage=0,name="AWWayofTime:incendium",stock=64},
    -- 	{label="Sanctus",damage=0,name="AWWayofTime:sanctus",stock=64},
    -- 	{label="Aether",damage=0,name="AWWayofTime:aether",stock=64},
    -- 	{label="Simple Catalyst",damage=0,name="AWWayofTime:simpleCatalyst",stock=64},
    -- 	{label="Terrae",damage=0,name="AWWayofTime:terrae",stock=64},
    -- 	{label="Aquasalus",damage=0,name="AWWayofTime:aquasalus",stock=64},
    -- 	{label="Tenebrae",damage=0,name="AWWayofTime:tennebrae",stock=64},
    -- 	{label="Offensa",damage=0,name="AWWayofTime:bloodMagicBaseAlchemyItems",stock=64},
    -- 	{label="Strengthened Catalyst",damage=3,name="AWWayofTime:bloodMagicBaseAlchemyItems",stock=64},
    -- 	{label="Creosote Bucket",damage=0,name="Railcraft:fluid.creosote.bucket",stock=1},
    -- 	{label="Enhanced Circuit Board",damage=1,name="Forestry:chipsets",stock=64},
    -- 	{label="Bronze Electron Tube",damage=2,name="Forestry:thermionicTubes",stock=64},
    -- 	{label="Golden Electron Tube",damage=4,name="Forestry:thermionicTubes",stock=64},
    -- 	{label="Emerald Electron Tube",damage=9,name="Forestry:thermionicTubes",stock=64},
    -- 	{label="Apatine Electron Tube",damage=10,name="Forestry:thermionicTubes",stock=64},
    -- 	{label="Ender Electron Tube",damage=12,name="Forestry:thermionicTubes",stock=64},
    -- 	{label="Ethanol Bucket",damage=0,name="Forestry:bucketEthanol",stock=1},
    -- 	{label="Item Conduit",damage=0,name="EnderIO:itemItemConduit",stock=64},
    -- 	{label="Raw \"SDHC-120\" Alloy",damage=0,name="dreamcraft:item.RawSDHCAlloy",stock=64},
    -- 	{label="Item Circuit Tier II",damage=0,name="dreamcraft:item.DiamondCoreChip",stock=64},
    -- 	{label="Alumino Silicate Wool",damage=0,name="dreamcraft:item.AluminoSilicateWool",stock=64},
    -- 	{label="Any MV Circuit",damage=0,name="dreamcraft:item.CircuitMV",stock=64},
    -- 	{label="Fluid Processor Tier I",damage=0,name="dreamcraft:item.EngineeringProcessorFluidDiamondCore",stock=64},
    -- 	{label="Mica Insulator Sheet",damage=0,name="dreamcraft:item.MicaInsulatorSheet",stock=64},
    -- 	{label="Essentia Processor Tier I",damage=0,name="dreamcraft:item.EngineeringProcessorEssentiaPulsatingCore",stock=64},
    -- 	{label="Mica Based Sheet",damage=0,name="dreamcraft:item.MicaBasedSheet",stock=64},
    -- 	{label="Fluid Circuit Tier I",damage=0,name="dreamcraft:item.DiamondFluidCoreChip",stock=64},
    -- 	{label="60K Cell",damage=0,name="dreamcraft:item.SixtyKCell",stock=64},
    -- 	{label="30K Cell",damage=0,name="dreamcraft:item.ThirtyKCell",stock=64},
    -- 	{label="Mica Based Pulp",damage=0,name="dreamcraft:item.MicaBasedPulp",stock=64},
    -- 	{label="Raw Lapotron Crystal",damage=0,name="dreamcraft:item.RawLapotronCrystal",stock=64},
    -- 	{label="Item Processor Tier II",damage=0,name="dreamcraft:item.EngineeringProcessorItemDiamondCore",stock=64},
    -- 	{label="Lapotron Dust",damage=0,name="dreamcraft:item.LapotronDust",stock=64},
    -- 	{label="10K Cell",damage=0,name="dreamcraft:item.TenKCell",stock=64},
    -- 	{label="Mica Insulator Foil",damage=0,name="dreamcraft:item.MicaInsulatorFoil",stock=64},
    -- 	{label="Essentia Circuit",damage=0,name="dreamcraft:item.EssentiaCircuit",stock=64},
    -- 	{label="Charged Certus Quartz Dust",damage=0,name="dreamcraft:item.ChargedCertusQuartzDust",stock=64},
    -- 	{label="Bucket of Nitric Acid",damage=0,name="dreamcraft:dreamcraft_NitricAcid_bucket",stock=1},
    -- 	{label="Rune of Water",damage=0,name="Botania:rune",stock=64},
    -- 	{label="Rune of Fire",damage=1,name="Botania:rune",stock=64},
    -- 	{label="Rune of Earth",damage=2,name="Botania:rune",stock=64},
    -- 	{label="Rune of Air",damage=3,name="Botania:rune",stock=64},
    -- 	{label="Rune of Spring",damage=4,name="Botania:rune",stock=64},
    -- 	{label="Rune of Summer",damage=5,name="Botania:rune",stock=64},
    -- 	{label="Rune of Autumn",damage=6,name="Botania:rune",stock=64},
    -- 	{label="Rune of Winter",damage=7,name="Botania:rune",stock=64},
    -- 	{label="Rune of Mana",damage=8,name="Botania:rune",stock=64},
    -- 	{label="Rune of Lust",damage=9,name="Botania:rune",stock=64},
    -- 	{label="Rune of Gluttony",damage=10,name="Botania:rune",stock=64},
    -- 	{label="Rune of Greed",damage=11,name="Botania:rune",stock=64},
    -- 	{label="Rune of Sloth",damage=12,name="Botania:rune",stock=64},
    -- 	{label="Rune of Wrath",damage=13,name="Botania:rune",stock=64},
    -- 	{label="Rune of Envy",damage=14,name="Botania:rune",stock=64},
    -- 	{label="Rune of Pride",damage=15,name="Botania:rune",stock=64},
    -- 	{label="Diamond Chipset",damage=3,name="BuildCraft|Silicon:redstoneChipset",stock=64},
    -- 	{label="Pulsating Chipset",damage=4,name="BuildCraft|Silicon:redstoneChipset",stock=64},
    -- 	{label="Tiny Pile of Indium Dust",damage=56,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tiny Pile of Platinum Dust",damage=85,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tiny Pile of Stainless Steel Dust",damage=306,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tiny Pile of Tungstensteel Dust",damage=316,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tiny Pile of Ashes",damage=815,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tiny Pile of Dark Ashes",damage=816,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Lithium Dust",damage=2006,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Carbon Dust",damage=2010,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Sodium Dust",damage=2017,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Magnesium Dust",damage=2018,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Raw Silicon Dust",damage=2020,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Palladium Dust",damage=2052,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Indium Dust",damage=2056,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tungsten Dust",damage=2081,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Osmium Dust",damage=2083,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Iridium Dust",damage=2084,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Platinum Dust",damage=2085,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Bronze Dust",damage=2300,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Electrum Dust",damage=2303,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Steel Dust",damage=2305,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Stainless Steel Dust",damage=2306,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Red Alloy Dust",damage=2308,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Nichrome Dust",damage=2311,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Soldering Alloy Dust",damage=2314,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tungstensteel Dust",damage=2316,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Enderium Dust",damage=2321,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Black Steel Dust",damage=2334,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Red Steel Dust",damage=2348,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Sterling Silver Dust",damage=2350,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Black Bronze Dust",damage=2352,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Vanadium-Gallium Dust",damage=2357,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Niobium-Titanium Dust",damage=2360,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Energetic Alloy Dust",damage=2366,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Conductive Iron Dust",damage=2369,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="HSS-G Dust",damage=2372,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="HSS-S Dust",damage=2374,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Rutile Dust",damage=2375,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Pulsating Iron Dust",damage=2378,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Enderium Base Dust",damage=2380,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Redstone Alloy Dust",damage=2381,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="TPV-Alloy Dust",damage=2576,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Magnesia Dust",damage=2621,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Sodium Bisulfate Dust",damage=2630,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Sodium Hydroxide Dust",damage=2685,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Sodium Sulfide Dust",damage=2719,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Salt",damage=2817,name="gregtech:gt.metaitem.01",stock=128},
     	{label="Graphene Dust",damage=2819,name="gregtech:gt.metaitem.01",stock=128},
    -- 	{label="Silicon Solar Grade (Poly SI) Dust",damage=2856,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Glass Dust",damage=2890,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Scheelite Dust",damage=2910,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Indium Gallium Phosphide Dust",damage=2981,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Superconductor Base IV Dust",damage=2990,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Purified Titanium Ore",damage=6028,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Naquadah Nugget",damage=9324,name="gregtech:gt.metaitem.01",stock=64},
    { label = "Aluminium Ingot", damage = 11019, name = "gregtech:gt.metaitem.01", stock = 512 },
     	{label="Titanium Ingot",damage=11028,name="gregtech:gt.metaitem.01",stock=128},
     	--{label="Cobalt Ingot",damage=11033,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Silver Ingot",damage=11054,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Neodymium Ingot",damage=11067,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Tantalum Ingot",damage=11080,name="gregtech:gt.metaitem.01",stock=128},
     	{label="Tungsten Ingot",damage=11081,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Iridium Ingot",damage=11084,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Platinum Ingot",damage=11085,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Bronze Ingot",damage=11300,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Electrum Ingot",damage=11303,name="gregtech:gt.metaitem.01",stock=64},
    { label = "Steel Ingot", damage = 11305, name = "gregtech:gt.metaitem.01", stock = 1024 },
    { label = "Stainless Steel Ingot", damage = 11306, name = "gregtech:gt.metaitem.01", stock = 128 },
    -- 	{label="Blue Alloy Ingot",damage=11309,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Cupronickel Ingot",damage=11310,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Nichrome Ingot",damage=11311,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Tungstensteel Ingot",damage=11316,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Enderium Ingot",damage=11321,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Naquadah Ingot",damage=11324,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Black Steel Ingot",damage=11334,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Meteoric Steel Ingot",damage=11341,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Vanadium-Gallium Ingot",damage=11357,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Energetic Alloy Ingot",damage=11366,name="gregtech:gt.metaitem.01",stock=128},
    -- 	{label="HSS-G Ingot",damage=11372,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="HSS-S Ingot",damage=11374,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Pulsating Iron Ingot",damage=11378,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Oriharukon Ingot",damage=11393,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Polytetrafluoroethylene Bar",damage=11473,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Polyphenylene Sulfide Ingot",damage=11631,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Polyvinyl Chloride Bar",damage=11649,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Silicon Solar Grade (Poly SI) Ingot",damage=11856,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Superconductor Base IV Ingot",damage=11990,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Aluminium Plate",damage=17019,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Titanium Plate",damage=17028,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Iron Plate",damage=17032,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Gold Plate",damage=17086,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Bronze Plate",damage=17300,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Steel Plate",damage=17305,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Stainless Steel Plate",damage=17306,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tungstensteel Plate",damage=17316,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Meteoric Iron Plate",damage=17340,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Pulsating Iron Plate",damage=17378,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Silicone Rubber Sheet",damage=17471,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Diamond Plate",damage=17500,name="gregtech:gt.metaitem.01",stock=32},
    -- 	{label="Fiber-Reinforced Epoxy Resin Sheet",damage=17610,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Polyvinyl Chloride Sheet",damage=17649,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Glowstone Plate",damage=17811,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Silicon Solar Grade (Poly SI) Plate",damage=17856,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Double Iron Plate",damage=18032,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Double Stainless Steel Plate",damage=18306,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Triple Aluminium Plate",damage=19019,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Triple Iridium Plate",damage=19084,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Triple Bronze Plate",damage=19300,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Triple Steel Plate",damage=19305,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Triple Tungstensteel Plate",damage=19316,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Triple Meteoric Iron Plate",damage=19340,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Triple Desh Plate",damage=19884,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Aluminium Rod",damage=23019,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Titanium Rod",damage=23028,name="gregtech:gt.metaitem.01",stock=32},
    -- 	{label="Chrome Rod",damage=23030,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Iron Rod",damage=23032,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Iridium Rod",damage=23084,name="gregtech:gt.metaitem.01",stock=64},
     	{label="Steel Rod",damage=23305,name="gregtech:gt.metaitem.01",stock=128},
     	{label="Stainless Steel Rod",damage=23306,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Meteoric Iron Rod",damage=23340,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Magnetic Iron Rod",damage=23354,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Magnetic Neodymium Rod",damage=23356,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Iron Ring",damage=28032,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Steel Ring",damage=28305,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Aluminium Foil",damage=29019,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Copper Foil",damage=29035,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Gallium Foil",damage=29037,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Tantalum Foil",damage=29080,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Gold Foil",damage=29086,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Electrum Foil",damage=29303,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Energetic Alloy Foil",damage=29366,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Polyphenylene Sulfide Foil",damage=29631,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Thin Polyvinyl Chloride Sheet",damage=29649,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="NAND Chip Array",damage=32081,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Heavy Duty Alloy Ingot T1",damage=32462,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Heavy Duty Alloy Ingot T2",damage=32463,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Large Battery Hull",damage=32502,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Large Lithium Battery",damage=32538,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Lapotronic Energy Orb",damage=32597,name="gregtech:gt.metaitem.01",stock=64},
    { label = "Electric Motor (LV)", damage = 32600, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Motor (MV)", damage = 32601, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Motor (HV)", damage = 32602, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Motor (EV)", damage = 32603, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Motor (IV)", damage = 32604, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Pump (MV)", damage = 32611, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Pump (HV)", damage = 32612, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Pump (EV)", damage = 32613, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Pump (IV)", damage = 32614, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Conveyor Module (LV)", damage = 32630, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Conveyor Module (MV)", damage = 32631, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Conveyor Module (HV)", damage = 32632, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Conveyor Module (EV)", damage = 32633, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Conveyor Module (IV)", damage = 32634, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Piston (LV)", damage = 32640, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Piston (MV)", damage = 32641, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Piston (HV)", damage = 32642, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Electric Piston (IV)", damage = 32644, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Robot Arm (LV)", damage = 32650, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Robot Arm (MV)", damage = 32651, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Robot Arm (HV)", damage = 32652, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Robot Arm (IV)", damage = 32654, name = "gregtech:gt.metaitem.01", stock = 2 },
    { label = "Field Generator (HV)", damage = 32672, name = "gregtech:gt.metaitem.01", stock = 2 },
    -- 	{label="Epoxy Circuit Board",damage=32711,name="gregtech:gt.metaitem.01",stock=64},
    -- 	{label="Engraved Lapotron Chip",damage=32714,name="gregtech:gt.metaitem.01",stock=64},
    { label = "Fiber-Reinforced Circuit Board", damage = 32720, name = "gregtech:gt.metaitem.01", stock = 64 },
    -- 	{label="Iridium Casing",damage=18084,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Stainless Steel Casing",damage=18306,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Tungstensteel Casing",damage=18316,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Tantalum Wire",damage=19080,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Iridium Wire",damage=19084,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Platinum Wire",damage=19085,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Electrum Wire",damage=19303,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Red Alloy Wire",damage=19308,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Tungstensteel Wire",damage=19316,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Annealed Copper Wire",damage=19345,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Fine Energetic Alloy Wire",damage=19366,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Tungstensteel Rotor",damage=21316,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Long Steel Rod",damage=22305,name="gregtech:gt.metaitem.02",stock=64},
    -- 	{label="Plastic Circuit Board",damage=32007,name="gregtech:gt.metaitem.03",stock=32},
     	{label="SMD Resistor",damage=32011,name="gregtech:gt.metaitem.03",stock=64},
     	{label="SMD Diode",damage=32016,name="gregtech:gt.metaitem.03",stock=64},
     	{label="SMD Transistor",damage=32018,name="gregtech:gt.metaitem.03",stock=64},
     	{label="SMD Capacitor",damage=32020,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Phosphorus doped Monocrystalline Silicon Boule",damage=32031,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Naquadah doped Monocrystalline Silicon Boule",damage=32032,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Phosphorus doped Wafer",damage=32034,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Naquadah doped Wafer",damage=32035,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Random Access Memory Chip (Wafer)",damage=32038,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Random Access Memory Chip",damage=32039,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="NOR Memory Chip (Wafer)",damage=32042,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="NOR Memory Chip",damage=32043,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Central Processing Unit (Wafer)",damage=32044,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Central Processing Unit",damage=32045,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="HPIC Wafer",damage=32052,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="High Power IC",damage=32053,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="NanoCPU Wafer",damage=32054,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Nanocomponent Central Processing Unit",damage=32055,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="QBit Wafer",damage=32056,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="QBit Processing Unit",damage=32057,name="gregtech:gt.metaitem.03",stock=64},
     	{label="NAND Chip",damage=32075,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Microprocessor",damage=32078,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Integrated Processor",damage=32080,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Nano Processor",damage=32082,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Quantum Processor",damage=32085,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Quantum Assembly",damage=32086,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Quantum Supercomputer",damage=32087,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Quantum Mainframe",damage=32088,name="gregtech:gt.metaitem.03",stock=8},
     	{label="Circuit Board",damage=32100,name="gregtech:gt.metaitem.03",stock=64},
     	{label="Advanced Circuit Board",damage=32102,name="gregtech:gt.metaitem.03",stock=64},
     	{label="More Advanced Circuit Board",damage=32103,name="gregtech:gt.metaitem.03",stock=64},
     	{label="Plastic Circuit Board",damage=32106,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="High Voltage Coil",damage=32143,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Extreme Voltage Coil",damage=32144,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Insane Voltage Coil",damage=32145,name="gregtech:gt.metaitem.03",stock=64},
     	{label="SMD Inductor",damage=32182,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="Gallium Arsenide Crystal",damage=32190,name="gregtech:gt.metaitem.03",stock=64},
    -- 	{label="60k He Coolant Cell",damage=0,name="gregtech:gt.60k_Helium_Coolantcell",stock=1},
    -- 	{label="180k He Coolant Cell",damage=0,name="gregtech:gt.180k_Helium_Coolantcell",stock=1},
    -- 	{label="Fuel Rod (Uranium)",damage=0,name="gregtech:gt.rodUranium",stock=8},
     	{label="Quad Fuel Rod (Uranium)",damage=0,name="gregtech:gt.rodUranium4",stock=8},
    -- 	{label="Fuel Rod (Mox)",damage=0,name="gregtech:gt.rodMOX",stock=64},
     	{label="Quad Fuel Rod (Mox)",damage=0,name="gregtech:gt.rodMOX4",stock=32},
    -- 	{label="Graphics Card (Tier 3)",damage=10,name="OpenComputers:item",stock=64},
    -- 	{label="Network Card",damage=11,name="OpenComputers:item",stock=64},
    -- 	{label="Wireless Network Card (Tier 2)",damage=13,name="OpenComputers:item",stock=64},
    -- 	{label="Microchip (Tier 1)",damage=24,name="OpenComputers:item",stock=64},
    -- 	{label="Microchip (Tier 2)",damage=25,name="OpenComputers:item",stock=64},
    -- 	{label="Microchip (Tier 3)",damage=26,name="OpenComputers:item",stock=64},
    -- 	{label="Arithmetic Logic Unit (ALU)",damage=27,name="OpenComputers:item",stock=64},
    -- 	{label="Control Unit (CU)",damage=28,name="OpenComputers:item",stock=64},
    -- 	{label="Memory (Tier 3)",damage=38,name="OpenComputers:item",stock=64},
    -- 	{label="Central Processing Unit (CPU) (Tier 3)",damage=43,name="OpenComputers:item",stock=64},
    -- 	{label="Inventory Upgrade",damage=53,name="OpenComputers:item",stock=64},
    -- 	{label="Inventory Controller Upgrade",damage=61,name="OpenComputers:item",stock=64},
    -- 	{label="Tank Upgrade",damage=76,name="OpenComputers:item",stock=64},
    -- 	{label="Tank Controller Upgrade",damage=77,name="OpenComputers:item",stock=64},
    -- 	{label="White Metal Dust",damage=0,name="miscutils:itemDustWhiteMetal",stock=64},
    -- 	{label="Sodium Nitrate Dust",damage=0,name="miscutils:itemDustSodiumNitrate",stock=64},
    -- 	{label="Zirconium Carbide Dust",damage=0,name="miscutils:itemDustZirconiumCarbide",stock=64},
    -- 	{label="Tumbaga Dust",damage=0,name="miscutils:itemDustTumbaga",stock=64},
    -- 	{label="Staballoy Dust",damage=0,name="miscutils:itemDustStaballoy",stock=64},
    -- 	{label="Eglin Steel Dust",damage=0,name="miscutils:itemDustEglinSteel",stock=64},
    -- 	{label="Stellite Ingot",damage=0,name="miscutils:itemIngotStellite",stock=64},
    -- 	{label="Stellite Dust",damage=0,name="miscutils:itemDustStellite",stock=64},
    -- 	{label="Talonite Dust",damage=0,name="miscutils:itemDustTalonite",stock=64},
    -- 	{label="Grisium Dust",damage=0,name="miscutils:itemDustGrisium",stock=64},
    -- 	{label="Growth Medium",damage=4,name="Genetics:misc",stock=64},
    -- 	{label="Integrated Circuit Board",damage=9,name="Genetics:misc",stock=64},
    -- 	{label="Draconium Ingot",damage=0,name="DraconicEvolution:draconiumIngot",stock=64},
    -- 	{label="Small Fuel Canister",damage=0,name="GalaxySpace:item.ModuleSmallFuelCanister",stock=64},
    -- 	{label="Compressed Dual Bronze",damage=0,name="GalaxySpace:item.CompressedDualBronze",stock=64},
    -- 	{label="Compressed Dual Aluminium",damage=0,name="GalaxySpace:item.CompressedDualAluminium",stock=64},
    -- 	{label="Compressed Alloy \"SDHC-120\"",damage=0,name="GalaxySpace:item.CompressedSDHD120",stock=64},
    -- 	{label="§61k§r ME Essentia Storage Component",damage=0,name="thaumicenergistics:storage.component",stock=64},
    -- 	{label="§e4k§r ME Essentia Storage Component",damage=1,name="thaumicenergistics:storage.component",stock=64},
    -- 	{label="§a16k§r ME Essentia Storage Component",damage=2,name="thaumicenergistics:storage.component",stock=64},
    -- 	{label="§b64k§r ME Essentia Storage Component",damage=3,name="thaumicenergistics:storage.component",stock=64},
    -- 	{label="Circuit Plate",damage=0,name="ProjRed|Core:projectred.core.part",stock=64},
    -- 	{label="Conductive Plate",damage=1,name="ProjRed|Core:projectred.core.part",stock=64},
    -- 	{label="Anode",damage=4,name="ProjRed|Core:projectred.core.part",stock=64},
    -- 	{label="Cathode",damage=5,name="ProjRed|Core:projectred.core.part",stock=64},
    -- 	{label="Platinum Salt Dust",damage=45,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Platinum Metallic Powder Dust",damage=47,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Platinum Residue Dust",damage=49,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Reprecipitated Platinum Dust",damage=51,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Potassium Disulfate Dust",damage=59,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Leach Residue Dust",damage=60,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Calcium Chloride Dust",damage=63,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Sodium Ruthenate Dust",damage=65,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Rarest Metal Residue Dust",damage=69,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Iridium Metal Residue Dust",damage=70,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Iridium Dioxide Dust",damage=73,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Iridium Chloride Dust",damage=76,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Rhodium Dust",damage=78,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Crude Rhodium Metal Dust",damage=79,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Rhodium Salt Dust",damage=80,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Rhodium Nitrate Dust",damage=83,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Rhodium Filter Cake Dust",damage=85,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Reprecipitated Rhodium Dust",damage=87,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Rhodium-Plated Palladium Dust",damage=88,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Tungstic Acid Dust",damage=29900,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Tungsten Trioxide Dust",damage=29901,name="bartworks:gt.bwMetaGenerateddust",stock=64},
    -- 	{label="Rhodium Ingot",damage=78,name="bartworks:gt.bwMetaGeneratedingot",stock=64},
    -- 	{label="Rhodium-Plated Palladium Ingot",damage=88,name="bartworks:gt.bwMetaGeneratedingot",stock=64},
}
return STOCKING
