local STOCKING = {
	{label="Quartz Glass", stock=64, name="appliedenergistics2:tile.BlockQuartzGlass", damage=0},
	{label="Clay", stock=64, name="minecraft:clay_ball", damage=0},
	{label="ME Interface", stock=64, name="appliedenergistics2:tile.BlockInterface", damage=0},
	{label="LV Machine Hull", stock=64, name="gregtech:gt.blockmachines", damage=11},
	{label="MV Machine Hull", stock=64, name="gregtech:gt.blockmachines", damage=12},
	{label="HV Machine Hull", stock=64, name="gregtech:gt.blockmachines", damage=13},
	{label="EV Machine Hull", stock=64, name="gregtech:gt.blockmachines", damage=14},
	{label="IV Machine Hull", stock=64, name="gregtech:gt.blockmachines", damage=15},
	{label="EV Dynamo Hatch", stock=64, name="gregtech:gt.blockmachines", damage=34},
	{label="EV Energy Hatch", stock=64, name="gregtech:gt.blockmachines", damage=44},
	{label="Input Bus (LV)", stock=64, name="gregtech:gt.blockmachines", damage=71},
	{label="Output Bus (LV)", stock=64, name="gregtech:gt.blockmachines", damage=81},
	{label="1x Lead Cable", stock=64, name="gregtech:gt.blockmachines", damage=1226},
	{label="1x Tin Wire", stock=64, name="gregtech:gt.blockmachines", damage=1240},
	{label="1x Tin Cable", stock=64, name="gregtech:gt.blockmachines", damage=1246},
	{label="2x Cupronickel Wire", stock=64, name="gregtech:gt.blockmachines", damage=1341},
	{label="1x Cupronickel Cable", stock=64, name="gregtech:gt.blockmachines", damage=1346},
	{label="1x Copper Wire", stock=64, name="gregtech:gt.blockmachines", damage=1360},
	{label="1x Copper Cable", stock=64, name="gregtech:gt.blockmachines", damage=1366},
	{label="4x Copper Cable", stock=64, name="gregtech:gt.blockmachines", damage=1368},
	{label="1x Annealed Copper Wire", stock=64, name="gregtech:gt.blockmachines", damage=1380},
	{label="1x Annealed Copper Cable", stock=64, name="gregtech:gt.blockmachines", damage=1386},
	{label="1x Gold Cable", stock=64, name="gregtech:gt.blockmachines", damage=1426},
	{label="2x Silver Wire", stock=64, name="gregtech:gt.blockmachines", damage=1461},
	{label="2x Silver Cable", stock=64, name="gregtech:gt.blockmachines", damage=1467},
	{label="1x Aluminium Wire", stock=64, name="gregtech:gt.blockmachines", damage=1580},
	{label="1x Aluminium Cable", stock=64, name="gregtech:gt.blockmachines", damage=1586},
	{label="1x Platinum Cable", stock=64, name="gregtech:gt.blockmachines", damage=1646},
	{label="1x Tungsten Wire", stock=64, name="gregtech:gt.blockmachines", damage=1680},
	{label="2x Tungsten Wire", stock=64, name="gregtech:gt.blockmachines", damage=1681},
	{label="1x Tungsten Cable", stock=64, name="gregtech:gt.blockmachines", damage=1686},
	{label="2x Tungsten Cable", stock=64, name="gregtech:gt.blockmachines", damage=1687},
	{label="LV Machine Casing", stock=64, name="gregtech:gt.blockcasings", damage=1},
	{label="HV Machine Casing", stock=64, name="gregtech:gt.blockcasings", damage=3},
	{label="EV Machine Casing", stock=64, name="gregtech:gt.blockcasings", damage=4},
	{label="IV Machine Casing", stock=64, name="gregtech:gt.blockcasings", damage=5},
	{label="Computer Case (Tier 3)", stock=64, name="OpenComputers:case3", damage=0},
	{label="Aluminium Frame Box", stock=64, name="gregtech:gt.blockframes", damage=19},
	{label="Tungstensteel Frame Box", stock=64, name="gregtech:gt.blockframes", damage=316},
	{label="Energium Dust", stock=64, name="IC2:itemDust2", damage=2},
	{label="Enriched Uranium Nuclear Fuel", stock=64, name="IC2:itemUran", damage=0},
	{label="Raw Carbon Fibre", stock=64, name="IC2:itemPartCarbonFibre", damage=0},
	{label="Water Cell", stock=64, name="IC2:itemCellEmpty", damage=1},
	{label="Coolant Cell", stock=64, name="IC2:itemCellEmpty", damage=9},
	{label="Distilled Water Cell", stock=64, name="IC2:itemCellEmpty", damage=12},
	{label="Industrial Diamond", stock=64, name="IC2:itemPartIndustrialDiamond", damage=0},
	{label="Fluix Crystal", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=7},
	{label="Fluix Dust", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=8},
	{label="Printed Calculation Circuit", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=16},
	{label="Printed Engineering Circuit", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=17},
	{label="Printed Logic Circuit", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=18},
	{label="Printed Silicon", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=20},
	{label="Logic Processor", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=22},
	{label="Calculation Processor", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=23},
	{label="Engineering Processor", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=24},
	{label="§a16k§r ME Storage Component", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=37},
	{label="Formation Core", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=43},
	{label="Annihilation Core", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=44},
	{label="Blank Pattern", stock=64, name="appliedenergistics2:item.ItemMultiMaterial", damage=52},
	{label="ME Glass Cable - Fluix", stock=64, name="appliedenergistics2:item.ItemMultiPart", damage=16},
	{label="ME Storage Bus", stock=64, name="appliedenergistics2:item.ItemMultiPart", damage=220},
	{label="ME Interface", stock=64, name="appliedenergistics2:item.ItemMultiPart", damage=440},
	{label="P2P Tunnel - ME", stock=64, name="appliedenergistics2:item.ItemMultiPart", damage=460},
	{label="Wet Concrete", stock=2304, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Wet Concrete", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Hydrochloric Acid", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Hydrochloric Acid", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Rhodium Sulfate", stock=360, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Rhodium Sulfate", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="3,3-Dichlorobenzidine", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of 3,3-Dichlorobenzidine", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Carbon Monoxide", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Carbon Monoxide", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Hydrogen", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Hydrogen", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Sodium Tungstate", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Sodium Tungstate", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Molten Polybenzimidazole", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Molten Polybenzimidazole", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Phthalic Acid", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Phthalic Acid", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="2-Nitrochlorobenzene", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of 2-Nitrochlorobenzene", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="IC2 Coolant", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of IC2 Coolant", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Chlorobenzene", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Chlorobenzene", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Diphenyl Isophthalate", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Diphenyl Isophthalate", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="Acidic Osmium Solution", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of Acidic Osmium Solution", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="3,3-Diaminobenzidine", stock=1000, is_fluid=true, name="ae2fc:fluid_drop", damage=0},
	{label="drop of 3,3-Diaminobenzidine", stock=64, name="ae2fc:fluid_drop", damage=0},
	{label="ME Dual Interface", stock=64, name="ae2fc:part_fluid_interface", damage=0},
	{label="ME Fluid Storage Bus", stock=64, name="ae2fc:part_fluid_storage_bus", damage=0},
	{label="Heavy Duty Plate", stock=64, name="GalacticraftCore:item.heavyPlating", damage=0},
	{label="Empty Canister", stock=1, name="GalacticraftCore:item.oilCanisterPartial", damage=1001},
	{label="Compressed Aluminum", stock=64, name="GalacticraftCore:item.basicItem", damage=8},
	{label="Compressed Steel", stock=64, name="GalacticraftCore:item.basicItem", damage=9},
	{label="Compressed Bronze", stock=64, name="GalacticraftCore:item.basicItem", damage=10},
	{label="Compressed Meteoric Iron", stock=64, name="GalacticraftCore:item.meteoricIronIngot", damage=1},
	{label="Heavy Duty Plate", stock=64, name="GalacticraftMars:item.itemBasicAsteroids", damage=0},
	{label="Compressed Titanium", stock=64, name="GalacticraftMars:item.itemBasicAsteroids", damage=6},
	{label="Heavy Duty Plate", stock=64, name="GalacticraftMars:item.null", damage=3},
	{label="Compressed Desh", stock=64, name="GalacticraftMars:item.null", damage=5},
	{label="Item Conduit", stock=64, name="EnderIO:itemItemConduit", damage=0},
	{label="Raw "SDHC-120" Alloy", stock=64, name="dreamcraft:item.RawSDHCAlloy", damage=0},
	{label="Fluid Processor Tier I", stock=64, name="dreamcraft:item.EngineeringProcessorFluidDiamondCore", damage=0},
	{label="Essentia Processor Tier I", stock=64, name="dreamcraft:item.EngineeringProcessorEssentiaPulsatingCore", damage=0},
	{label="Fluid Circuit Tier I", stock=64, name="dreamcraft:item.DiamondFluidCoreChip", damage=0},
	{label="60K Cell", stock=64, name="dreamcraft:item.SixtyKCell", damage=0},
	{label="30K Cell", stock=64, name="dreamcraft:item.ThirtyKCell", damage=0},
	{label="Lapotron Dust", stock=64, name="dreamcraft:item.LapotronDust", damage=0},
	{label="Essentia Circuit", stock=64, name="dreamcraft:item.EssentiaCircuit", damage=0},
	{label="Charged Certus Quartz Dust", stock=64, name="dreamcraft:item.ChargedCertusQuartzDust", damage=0},
	{label="Diamond Chipset", stock=64, name="BuildCraft|Silicon:redstoneChipset", damage=3},
	{label="Pulsating Chipset", stock=64, name="BuildCraft|Silicon:redstoneChipset", damage=4},
	{label="Tiny Pile of Platinum Dust", stock=64, name="gregtech:gt.metaitem.01", damage=85},
	{label="Tiny Pile of Stainless Steel Dust", stock=64, name="gregtech:gt.metaitem.01", damage=306},
	{label="Tiny Pile of Tungstensteel Dust", stock=64, name="gregtech:gt.metaitem.01", damage=316},
	{label="Tiny Pile of Ashes", stock=64, name="gregtech:gt.metaitem.01", damage=815},
	{label="Tiny Pile of Dark Ashes", stock=64, name="gregtech:gt.metaitem.01", damage=816},
	{label="Lithium Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2006},
	{label="Tungsten Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2081},
	{label="Bronze Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2300},
	{label="Electrum Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2303},
	{label="Stainless Steel Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2306},
	{label="Red Alloy Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2308},
	{label="Nichrome Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2311},
	{label="Tungstensteel Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2316},
	{label="Black Steel Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2334},
	{label="Red Steel Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2348},
	{label="Black Bronze Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2352},
	{label="Niobium-Titanium Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2360},
	{label="Energetic Alloy Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2366},
	{label="Conductive Iron Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2369},
	{label="Rutile Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2375},
	{label="Magnesiumchloride Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2377},
	{label="TPV-Alloy Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2576},
	{label="Sodium Hydroxide Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2685},
	{label="Salt", stock=64, name="gregtech:gt.metaitem.01", damage=2817},
	{label="Scheelite Dust", stock=64, name="gregtech:gt.metaitem.01", damage=2910},
	{label="Wrought Iron Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=11304},
	{label="Steel Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=11305},
	{label="Blue Alloy Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=11309},
	{label="Meteoric Steel Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=11341},
	{label="Energetic Alloy Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=11366},
	{label="Hot Titanium Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=12028},
	{label="Hot Tantalum Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=12080},
	{label="Hot Tungstensteel Ingot", stock=64, name="gregtech:gt.metaitem.01", damage=12316},
	{label="Aluminium Plate", stock=64, name="gregtech:gt.metaitem.01", damage=17019},
	{label="Titanium Plate", stock=64, name="gregtech:gt.metaitem.01", damage=17028},
	{label="Steel Plate", stock=64, name="gregtech:gt.metaitem.01", damage=17305},
	{label="Stainless Steel Plate", stock=64, name="gregtech:gt.metaitem.01", damage=17306},
	{label="Meteoric Iron Plate", stock=64, name="gregtech:gt.metaitem.01", damage=17340},
	{label="Silicone Rubber Sheet", stock=64, name="gregtech:gt.metaitem.01", damage=17471},
	{label="Fiber-Reinforced Epoxy Resin Sheet", stock=64, name="gregtech:gt.metaitem.01", damage=17610},
	{label="Silicon Solar Grade (Poly SI) Plate", stock=64, name="gregtech:gt.metaitem.01", damage=17856},
	{label="Triple Aluminium Plate", stock=64, name="gregtech:gt.metaitem.01", damage=19019},
	{label="Triple Bronze Plate", stock=64, name="gregtech:gt.metaitem.01", damage=19300},
	{label="Triple Steel Plate", stock=64, name="gregtech:gt.metaitem.01", damage=19305},
	{label="Triple Meteoric Iron Plate", stock=64, name="gregtech:gt.metaitem.01", damage=19340},
	{label="Triple Desh Plate", stock=64, name="gregtech:gt.metaitem.01", damage=19884},
	{label="Aluminium Rod", stock=64, name="gregtech:gt.metaitem.01", damage=23019},
	{label="Chrome Rod", stock=64, name="gregtech:gt.metaitem.01", damage=23030},
	{label="Iron Rod", stock=64, name="gregtech:gt.metaitem.01", damage=23032},
	{label="Steel Rod", stock=64, name="gregtech:gt.metaitem.01", damage=23305},
	{label="Meteoric Iron Rod", stock=64, name="gregtech:gt.metaitem.01", damage=23340},
	{label="Iron Ring", stock=64, name="gregtech:gt.metaitem.01", damage=28032},
	{label="Steel Ring", stock=64, name="gregtech:gt.metaitem.01", damage=28305},
	{label="Silicone Rubber Ring", stock=64, name="gregtech:gt.metaitem.01", damage=28471},
	{label="Aluminium Foil", stock=64, name="gregtech:gt.metaitem.01", damage=29019},
	{label="Energetic Alloy Foil", stock=64, name="gregtech:gt.metaitem.01", damage=29366},
	{label="NAND Chip Array", stock=64, name="gregtech:gt.metaitem.01", damage=32081},
	{label="Heavy Duty Alloy Ingot T1", stock=64, name="gregtech:gt.metaitem.01", damage=32462},
	{label="Heavy Duty Alloy Ingot T2", stock=64, name="gregtech:gt.metaitem.01", damage=32463},
	{label="Electric Motor (LV)", stock=64, name="gregtech:gt.metaitem.01", damage=32600},
	{label="Electric Motor (MV)", stock=64, name="gregtech:gt.metaitem.01", damage=32601},
	{label="Electric Motor (HV)", stock=64, name="gregtech:gt.metaitem.01", damage=32602},
	{label="Electric Motor (EV)", stock=64, name="gregtech:gt.metaitem.01", damage=32603},
	{label="Electric Motor (IV)", stock=64, name="gregtech:gt.metaitem.01", damage=32604},
	{label="Electric Pump (MV)", stock=64, name="gregtech:gt.metaitem.01", damage=32611},
	{label="Electric Pump (EV)", stock=64, name="gregtech:gt.metaitem.01", damage=32613},
	{label="Electric Pump (IV)", stock=64, name="gregtech:gt.metaitem.01", damage=32614},
	{label="Conveyor Module (LV)", stock=64, name="gregtech:gt.metaitem.01", damage=32630},
	{label="Conveyor Module (MV)", stock=64, name="gregtech:gt.metaitem.01", damage=32631},
	{label="Conveyor Module (HV)", stock=64, name="gregtech:gt.metaitem.01", damage=32632},
	{label="Conveyor Module (IV)", stock=64, name="gregtech:gt.metaitem.01", damage=32634},
	{label="Electric Piston (LV)", stock=64, name="gregtech:gt.metaitem.01", damage=32640},
	{label="Electric Piston (MV)", stock=64, name="gregtech:gt.metaitem.01", damage=32641},
	{label="Electric Piston (HV)", stock=64, name="gregtech:gt.metaitem.01", damage=32642},
	{label="Electric Piston (IV)", stock=64, name="gregtech:gt.metaitem.01", damage=32644},
	{label="Robot Arm (LV)", stock=64, name="gregtech:gt.metaitem.01", damage=32650},
	{label="Robot Arm (MV)", stock=64, name="gregtech:gt.metaitem.01", damage=32651},
	{label="Robot Arm (HV)", stock=64, name="gregtech:gt.metaitem.01", damage=32652},
	{label="Robot Arm (IV)", stock=64, name="gregtech:gt.metaitem.01", damage=32654},
	{label="Processor Assembly", stock=64, name="gregtech:gt.metaitem.01", damage=32703},
	{label="Workstation", stock=64, name="gregtech:gt.metaitem.01", damage=32704},
	{label="Mainframe", stock=64, name="gregtech:gt.metaitem.01", damage=32705},
	{label="Nano Mainframe", stock=64, name="gregtech:gt.metaitem.01", damage=32706},
	{label="Fiber-Reinforced Circuit Board", stock=64, name="gregtech:gt.metaitem.01", damage=32720},
	{label="Long Steel Rod", stock=64, name="gregtech:gt.metaitem.02", damage=22305},
	{label="SMD Resistor", stock=64, name="gregtech:gt.metaitem.03", damage=32011},
	{label="SMD Diode", stock=64, name="gregtech:gt.metaitem.03", damage=32016},
	{label="SMD Transistor", stock=64, name="gregtech:gt.metaitem.03", damage=32018},
	{label="SMD Capacitor", stock=64, name="gregtech:gt.metaitem.03", damage=32020},
	{label="Phosphorus doped Monocrystalline Silicon Boule", stock=64, name="gregtech:gt.metaitem.03", damage=32031},
	{label="Microprocessor", stock=64, name="gregtech:gt.metaitem.03", damage=32078},
	{label="Integrated Processor", stock=64, name="gregtech:gt.metaitem.03", damage=32080},
	{label="Nano Supercomputer", stock=64, name="gregtech:gt.metaitem.03", damage=32084},
	{label="More Advanced Circuit Board", stock=64, name="gregtech:gt.metaitem.03", damage=32103},
	{label="Extreme Voltage Coil", stock=64, name="gregtech:gt.metaitem.03", damage=32144},
	{label="Fuel Rod (Uranium)", stock=64, name="gregtech:gt.rodUranium", damage=0},
	{label="Quad Fuel Rod (Uranium)", stock=64, name="gregtech:gt.rodUranium4", damage=0},
	{label="Memory (Tier 1)", stock=64, name="OpenComputers:item", damage=1},
	{label="Graphics Card (Tier 3)", stock=64, name="OpenComputers:item", damage=10},
	{label="Microchip (Tier 1)", stock=64, name="OpenComputers:item", damage=24},
	{label="Microchip (Tier 3)", stock=64, name="OpenComputers:item", damage=26},
	{label="Arithmetic Logic Unit (ALU)", stock=64, name="OpenComputers:item", damage=27},
	{label="Control Unit (CU)", stock=64, name="OpenComputers:item", damage=28},
	{label="Card Base", stock=64, name="OpenComputers:item", damage=33},
	{label="Memory (Tier 3)", stock=64, name="OpenComputers:item", damage=38},
	{label="Central Processing Unit (CPU) (Tier 3)", stock=64, name="OpenComputers:item", damage=43},
	{label="EEPROM", stock=64, name="OpenComputers:eeprom", damage=0},
	{label="White Metal Dust", stock=64, name="miscutils:itemDustWhiteMetal", damage=0},
	{label="Eglin Steel Dust", stock=64, name="miscutils:itemDustEglinSteel", damage=0},
	{label="Talonite Dust", stock=64, name="miscutils:itemDustTalonite", damage=0},
	{label="Small Fuel Canister", stock=64, name="GalaxySpace:item.ModuleSmallFuelCanister", damage=0},
	{label="Compressed Dual Bronze", stock=64, name="GalaxySpace:item.CompressedDualBronze", damage=0},
	{label="Compressed Dual Aluminium", stock=64, name="GalaxySpace:item.CompressedDualAluminium", damage=0},
	{label="Compressed Alloy "SDHC-120"", stock=64, name="GalaxySpace:item.CompressedSDHD120", damage=0},
	{label="Circuit Plate", stock=64, name="ProjRed|Core:projectred.core.part", damage=0},
	{label="Conductive Plate", stock=64, name="ProjRed|Core:projectred.core.part", damage=1},
	{label="Cathode", stock=64, name="ProjRed|Core:projectred.core.part", damage=5},
	{label="Potassium Disulfate Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=59},
	{label="Leach Residue Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=60},
	{label="Calcium Chloride Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=63},
	{label="Sodium Ruthenate Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=65},
	{label="Rarest Metal Residue Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=69},
	{label="Iridium Metal Residue Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=70},
	{label="Tungstic Acid Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=29900},
	{label="Tungsten Trioxide Dust", stock=64, name="bartworks:gt.bwMetaGenerateddust", damage=29901},
}
